# This file was automatically generated by SWIG (http://www.swig.org).
# Version 3.0.10
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.





from sys import version_info as _swig_python_version_info
if _swig_python_version_info >= (2, 7, 0):
    def swig_import_helper():
        import importlib
        pkg = __name__.rpartition('.')[0]
        mname = '.'.join((pkg, '_btrievePython')).lstrip('.')
        try:
            return importlib.import_module(mname)
        except ImportError:
            return importlib.import_module('_btrievePython')
    _btrievePython = swig_import_helper()
    del swig_import_helper
elif _swig_python_version_info >= (2, 6, 0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_btrievePython', [dirname(__file__)])
        except ImportError:
            import _btrievePython
            return _btrievePython
        if fp is not None:
            try:
                _mod = imp.load_module('_btrievePython', fp, pathname, description)
            finally:
                fp.close()
            return _mod
    _btrievePython = swig_import_helper()
    del swig_import_helper
else:
    import _btrievePython
del _swig_python_version_info
try:
    _swig_property = property
except NameError:
    pass  # Python < 2.2 doesn't have 'property'.

try:
    import builtins as __builtin__
except ImportError:
    import __builtin__

def _swig_setattr_nondynamic(self, class_type, name, value, static=1):
    if (name == "thisown"):
        return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name, None)
    if method:
        return method(self, value)
    if (not static):
        if _newclass:
            object.__setattr__(self, name, value)
        else:
            self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)


def _swig_setattr(self, class_type, name, value):
    return _swig_setattr_nondynamic(self, class_type, name, value, 0)


def _swig_getattr(self, class_type, name):
    if (name == "thisown"):
        return self.this.own()
    method = class_type.__swig_getmethods__.get(name, None)
    if method:
        return method(self)
    raise AttributeError("'%s' object has no attribute '%s'" % (class_type.__name__, name))


def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except __builtin__.Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except __builtin__.Exception:
    class _object:
        pass
    _newclass = 0


def buffer_view_attach(view, obj, buffer, size):
    return _btrievePython.buffer_view_attach(view, obj, buffer, size)
buffer_view_attach = _btrievePython.buffer_view_attach
class Btrieve(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, Btrieve, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, Btrieve, name)

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined")
    __repr__ = _swig_repr
    MAXIMUM_RECORD_LENGTH = _btrievePython.Btrieve_MAXIMUM_RECORD_LENGTH
    MAXIMUM_KEY_LENGTH = _btrievePython.Btrieve_MAXIMUM_KEY_LENGTH
    ACS_MODE_NONE = _btrievePython.Btrieve_ACS_MODE_NONE
    ACS_MODE_NAMED = _btrievePython.Btrieve_ACS_MODE_NAMED
    ACS_MODE_NUMBERED = _btrievePython.Btrieve_ACS_MODE_NUMBERED
    ACS_MODE_CASE_INSENSITIVE = _btrievePython.Btrieve_ACS_MODE_CASE_INSENSITIVE
    ACS_MODE_DEFAULT = _btrievePython.Btrieve_ACS_MODE_DEFAULT
    ACS_MODE_UNKNOWN = _btrievePython.Btrieve_ACS_MODE_UNKNOWN
    CREATE_MODE_OVERWRITE = _btrievePython.Btrieve_CREATE_MODE_OVERWRITE
    CREATE_MODE_NO_OVERWRITE = _btrievePython.Btrieve_CREATE_MODE_NO_OVERWRITE
    CREATE_MODE_UNKNOWN = _btrievePython.Btrieve_CREATE_MODE_UNKNOWN
    COMPARISON_NONE = _btrievePython.Btrieve_COMPARISON_NONE
    COMPARISON_EQUAL = _btrievePython.Btrieve_COMPARISON_EQUAL
    COMPARISON_GREATER_THAN = _btrievePython.Btrieve_COMPARISON_GREATER_THAN
    COMPARISON_LESS_THAN = _btrievePython.Btrieve_COMPARISON_LESS_THAN
    COMPARISON_NOT_EQUAL = _btrievePython.Btrieve_COMPARISON_NOT_EQUAL
    COMPARISON_GREATER_THAN_OR_EQUAL = _btrievePython.Btrieve_COMPARISON_GREATER_THAN_OR_EQUAL
    COMPARISON_LESS_THAN_OR_EQUAL = _btrievePython.Btrieve_COMPARISON_LESS_THAN_OR_EQUAL
    COMPARISON_LIKE = _btrievePython.Btrieve_COMPARISON_LIKE
    COMPARISON_NOT_LIKE = _btrievePython.Btrieve_COMPARISON_NOT_LIKE
    COMPARISON_UNKNOWN = _btrievePython.Btrieve_COMPARISON_UNKNOWN
    CONNECTOR_LAST = _btrievePython.Btrieve_CONNECTOR_LAST
    CONNECTOR_AND = _btrievePython.Btrieve_CONNECTOR_AND
    CONNECTOR_OR = _btrievePython.Btrieve_CONNECTOR_OR
    CONNECTOR_UNKNOWN = _btrievePython.Btrieve_CONNECTOR_UNKNOWN
    DISK_DRIVE_A = _btrievePython.Btrieve_DISK_DRIVE_A
    DISK_DRIVE_B = _btrievePython.Btrieve_DISK_DRIVE_B
    DISK_DRIVE_C = _btrievePython.Btrieve_DISK_DRIVE_C
    DISK_DRIVE_D = _btrievePython.Btrieve_DISK_DRIVE_D
    DISK_DRIVE_E = _btrievePython.Btrieve_DISK_DRIVE_E
    DISK_DRIVE_F = _btrievePython.Btrieve_DISK_DRIVE_F
    DISK_DRIVE_G = _btrievePython.Btrieve_DISK_DRIVE_G
    DISK_DRIVE_H = _btrievePython.Btrieve_DISK_DRIVE_H
    DISK_DRIVE_I = _btrievePython.Btrieve_DISK_DRIVE_I
    DISK_DRIVE_J = _btrievePython.Btrieve_DISK_DRIVE_J
    DISK_DRIVE_K = _btrievePython.Btrieve_DISK_DRIVE_K
    DISK_DRIVE_L = _btrievePython.Btrieve_DISK_DRIVE_L
    DISK_DRIVE_M = _btrievePython.Btrieve_DISK_DRIVE_M
    DISK_DRIVE_N = _btrievePython.Btrieve_DISK_DRIVE_N
    DISK_DRIVE_O = _btrievePython.Btrieve_DISK_DRIVE_O
    DISK_DRIVE_P = _btrievePython.Btrieve_DISK_DRIVE_P
    DISK_DRIVE_Q = _btrievePython.Btrieve_DISK_DRIVE_Q
    DISK_DRIVE_R = _btrievePython.Btrieve_DISK_DRIVE_R
    DISK_DRIVE_S = _btrievePython.Btrieve_DISK_DRIVE_S
    DISK_DRIVE_T = _btrievePython.Btrieve_DISK_DRIVE_T
    DISK_DRIVE_U = _btrievePython.Btrieve_DISK_DRIVE_U
    DISK_DRIVE_V = _btrievePython.Btrieve_DISK_DRIVE_V
    DISK_DRIVE_W = _btrievePython.Btrieve_DISK_DRIVE_W
    DISK_DRIVE_X = _btrievePython.Btrieve_DISK_DRIVE_X
    DISK_DRIVE_Y = _btrievePython.Btrieve_DISK_DRIVE_Y
    DISK_DRIVE_Z = _btrievePython.Btrieve_DISK_DRIVE_Z
    DISK_DRIVE_DEFAULT = _btrievePython.Btrieve_DISK_DRIVE_DEFAULT
    DISK_DRIVE_UNKNOWN = _btrievePython.Btrieve_DISK_DRIVE_UNKNOWN
    DUPLICATE_MODE_NOT_ALLOWED = _btrievePython.Btrieve_DUPLICATE_MODE_NOT_ALLOWED
    DUPLICATE_MODE_ALLOWED_NONREPEATING = _btrievePython.Btrieve_DUPLICATE_MODE_ALLOWED_NONREPEATING
    DUPLICATE_MODE_ALLOWED_REPEATING = _btrievePython.Btrieve_DUPLICATE_MODE_ALLOWED_REPEATING
    DUPLICATE_MODE_UNKNOWN = _btrievePython.Btrieve_DUPLICATE_MODE_UNKNOWN
    DATA_TYPE_CHAR = _btrievePython.Btrieve_DATA_TYPE_CHAR
    DATA_TYPE_ZSTRING = _btrievePython.Btrieve_DATA_TYPE_ZSTRING
    DATA_TYPE_INTEGER = _btrievePython.Btrieve_DATA_TYPE_INTEGER
    DATA_TYPE_UNSIGNED_BINARY = _btrievePython.Btrieve_DATA_TYPE_UNSIGNED_BINARY
    DATA_TYPE_FLOAT = _btrievePython.Btrieve_DATA_TYPE_FLOAT
    DATA_TYPE_AUTOINCREMENT = _btrievePython.Btrieve_DATA_TYPE_AUTOINCREMENT
    DATA_TYPE_DATE = _btrievePython.Btrieve_DATA_TYPE_DATE
    DATA_TYPE_NUMERICSTS = _btrievePython.Btrieve_DATA_TYPE_NUMERICSTS
    DATA_TYPE_TIME = _btrievePython.Btrieve_DATA_TYPE_TIME
    DATA_TYPE_NUMERICSA = _btrievePython.Btrieve_DATA_TYPE_NUMERICSA
    DATA_TYPE_DECIMAL = _btrievePython.Btrieve_DATA_TYPE_DECIMAL
    DATA_TYPE_CURRENCY = _btrievePython.Btrieve_DATA_TYPE_CURRENCY
    DATA_TYPE_MONEY = _btrievePython.Btrieve_DATA_TYPE_MONEY
    DATA_TYPE_TIMESTAMP = _btrievePython.Btrieve_DATA_TYPE_TIMESTAMP
    DATA_TYPE_LOGICAL = _btrievePython.Btrieve_DATA_TYPE_LOGICAL
    DATA_TYPE_WSTRING = _btrievePython.Btrieve_DATA_TYPE_WSTRING
    DATA_TYPE_NUMERIC = _btrievePython.Btrieve_DATA_TYPE_NUMERIC
    DATA_TYPE_WZSTRING = _btrievePython.Btrieve_DATA_TYPE_WZSTRING
    DATA_TYPE_BFLOAT = _btrievePython.Btrieve_DATA_TYPE_BFLOAT
    DATA_TYPE_GUID = _btrievePython.Btrieve_DATA_TYPE_GUID
    DATA_TYPE_LSTRING = _btrievePython.Btrieve_DATA_TYPE_LSTRING
    DATA_TYPE_NULL_INDICATOR_SEGMENT = _btrievePython.Btrieve_DATA_TYPE_NULL_INDICATOR_SEGMENT
    DATA_TYPE_LEGACY_STRING = _btrievePython.Btrieve_DATA_TYPE_LEGACY_STRING
    DATA_TYPE_LEGACY_BINARY = _btrievePython.Btrieve_DATA_TYPE_LEGACY_BINARY
    DATA_TYPE_UNKNOWN = _btrievePython.Btrieve_DATA_TYPE_UNKNOWN
    FILE_VERSION_6_0 = _btrievePython.Btrieve_FILE_VERSION_6_0
    FILE_VERSION_6_1 = _btrievePython.Btrieve_FILE_VERSION_6_1
    FILE_VERSION_7_0 = _btrievePython.Btrieve_FILE_VERSION_7_0
    FILE_VERSION_8_0 = _btrievePython.Btrieve_FILE_VERSION_8_0
    FILE_VERSION_9_0 = _btrievePython.Btrieve_FILE_VERSION_9_0
    FILE_VERSION_9_5 = _btrievePython.Btrieve_FILE_VERSION_9_5
    FILE_VERSION_DEFAULT = _btrievePython.Btrieve_FILE_VERSION_DEFAULT
    FILE_VERSION_UNKNOWN = _btrievePython.Btrieve_FILE_VERSION_UNKNOWN
    FREE_SPACE_THRESHOLD_10_PERCENT = _btrievePython.Btrieve_FREE_SPACE_THRESHOLD_10_PERCENT
    FREE_SPACE_THRESHOLD_20_PERCENT = _btrievePython.Btrieve_FREE_SPACE_THRESHOLD_20_PERCENT
    FREE_SPACE_THRESHOLD_30_PERCENT = _btrievePython.Btrieve_FREE_SPACE_THRESHOLD_30_PERCENT
    FREE_SPACE_THRESHOLD_DEFAULT = _btrievePython.Btrieve_FREE_SPACE_THRESHOLD_DEFAULT
    FREE_SPACE_THRESHOLD_UNKNOWN = _btrievePython.Btrieve_FREE_SPACE_THRESHOLD_UNKNOWN
    INDEX_1 = _btrievePython.Btrieve_INDEX_1
    INDEX_2 = _btrievePython.Btrieve_INDEX_2
    INDEX_3 = _btrievePython.Btrieve_INDEX_3
    INDEX_4 = _btrievePython.Btrieve_INDEX_4
    INDEX_5 = _btrievePython.Btrieve_INDEX_5
    INDEX_6 = _btrievePython.Btrieve_INDEX_6
    INDEX_7 = _btrievePython.Btrieve_INDEX_7
    INDEX_8 = _btrievePython.Btrieve_INDEX_8
    INDEX_9 = _btrievePython.Btrieve_INDEX_9
    INDEX_10 = _btrievePython.Btrieve_INDEX_10
    INDEX_11 = _btrievePython.Btrieve_INDEX_11
    INDEX_12 = _btrievePython.Btrieve_INDEX_12
    INDEX_13 = _btrievePython.Btrieve_INDEX_13
    INDEX_14 = _btrievePython.Btrieve_INDEX_14
    INDEX_15 = _btrievePython.Btrieve_INDEX_15
    INDEX_16 = _btrievePython.Btrieve_INDEX_16
    INDEX_17 = _btrievePython.Btrieve_INDEX_17
    INDEX_18 = _btrievePython.Btrieve_INDEX_18
    INDEX_19 = _btrievePython.Btrieve_INDEX_19
    INDEX_20 = _btrievePython.Btrieve_INDEX_20
    INDEX_21 = _btrievePython.Btrieve_INDEX_21
    INDEX_22 = _btrievePython.Btrieve_INDEX_22
    INDEX_23 = _btrievePython.Btrieve_INDEX_23
    INDEX_24 = _btrievePython.Btrieve_INDEX_24
    INDEX_25 = _btrievePython.Btrieve_INDEX_25
    INDEX_26 = _btrievePython.Btrieve_INDEX_26
    INDEX_27 = _btrievePython.Btrieve_INDEX_27
    INDEX_28 = _btrievePython.Btrieve_INDEX_28
    INDEX_29 = _btrievePython.Btrieve_INDEX_29
    INDEX_30 = _btrievePython.Btrieve_INDEX_30
    INDEX_31 = _btrievePython.Btrieve_INDEX_31
    INDEX_32 = _btrievePython.Btrieve_INDEX_32
    INDEX_33 = _btrievePython.Btrieve_INDEX_33
    INDEX_34 = _btrievePython.Btrieve_INDEX_34
    INDEX_35 = _btrievePython.Btrieve_INDEX_35
    INDEX_36 = _btrievePython.Btrieve_INDEX_36
    INDEX_37 = _btrievePython.Btrieve_INDEX_37
    INDEX_38 = _btrievePython.Btrieve_INDEX_38
    INDEX_39 = _btrievePython.Btrieve_INDEX_39
    INDEX_40 = _btrievePython.Btrieve_INDEX_40
    INDEX_41 = _btrievePython.Btrieve_INDEX_41
    INDEX_42 = _btrievePython.Btrieve_INDEX_42
    INDEX_43 = _btrievePython.Btrieve_INDEX_43
    INDEX_44 = _btrievePython.Btrieve_INDEX_44
    INDEX_45 = _btrievePython.Btrieve_INDEX_45
    INDEX_46 = _btrievePython.Btrieve_INDEX_46
    INDEX_47 = _btrievePython.Btrieve_INDEX_47
    INDEX_48 = _btrievePython.Btrieve_INDEX_48
    INDEX_49 = _btrievePython.Btrieve_INDEX_49
    INDEX_50 = _btrievePython.Btrieve_INDEX_50
    INDEX_51 = _btrievePython.Btrieve_INDEX_51
    INDEX_52 = _btrievePython.Btrieve_INDEX_52
    INDEX_53 = _btrievePython.Btrieve_INDEX_53
    INDEX_54 = _btrievePython.Btrieve_INDEX_54
    INDEX_55 = _btrievePython.Btrieve_INDEX_55
    INDEX_56 = _btrievePython.Btrieve_INDEX_56
    INDEX_57 = _btrievePython.Btrieve_INDEX_57
    INDEX_58 = _btrievePython.Btrieve_INDEX_58
    INDEX_59 = _btrievePython.Btrieve_INDEX_59
    INDEX_60 = _btrievePython.Btrieve_INDEX_60
    INDEX_61 = _btrievePython.Btrieve_INDEX_61
    INDEX_62 = _btrievePython.Btrieve_INDEX_62
    INDEX_63 = _btrievePython.Btrieve_INDEX_63
    INDEX_64 = _btrievePython.Btrieve_INDEX_64
    INDEX_65 = _btrievePython.Btrieve_INDEX_65
    INDEX_66 = _btrievePython.Btrieve_INDEX_66
    INDEX_67 = _btrievePython.Btrieve_INDEX_67
    INDEX_68 = _btrievePython.Btrieve_INDEX_68
    INDEX_69 = _btrievePython.Btrieve_INDEX_69
    INDEX_70 = _btrievePython.Btrieve_INDEX_70
    INDEX_71 = _btrievePython.Btrieve_INDEX_71
    INDEX_72 = _btrievePython.Btrieve_INDEX_72
    INDEX_73 = _btrievePython.Btrieve_INDEX_73
    INDEX_74 = _btrievePython.Btrieve_INDEX_74
    INDEX_75 = _btrievePython.Btrieve_INDEX_75
    INDEX_76 = _btrievePython.Btrieve_INDEX_76
    INDEX_77 = _btrievePython.Btrieve_INDEX_77
    INDEX_78 = _btrievePython.Btrieve_INDEX_78
    INDEX_79 = _btrievePython.Btrieve_INDEX_79
    INDEX_80 = _btrievePython.Btrieve_INDEX_80
    INDEX_81 = _btrievePython.Btrieve_INDEX_81
    INDEX_82 = _btrievePython.Btrieve_INDEX_82
    INDEX_83 = _btrievePython.Btrieve_INDEX_83
    INDEX_84 = _btrievePython.Btrieve_INDEX_84
    INDEX_85 = _btrievePython.Btrieve_INDEX_85
    INDEX_86 = _btrievePython.Btrieve_INDEX_86
    INDEX_87 = _btrievePython.Btrieve_INDEX_87
    INDEX_88 = _btrievePython.Btrieve_INDEX_88
    INDEX_89 = _btrievePython.Btrieve_INDEX_89
    INDEX_90 = _btrievePython.Btrieve_INDEX_90
    INDEX_91 = _btrievePython.Btrieve_INDEX_91
    INDEX_92 = _btrievePython.Btrieve_INDEX_92
    INDEX_93 = _btrievePython.Btrieve_INDEX_93
    INDEX_94 = _btrievePython.Btrieve_INDEX_94
    INDEX_95 = _btrievePython.Btrieve_INDEX_95
    INDEX_96 = _btrievePython.Btrieve_INDEX_96
    INDEX_97 = _btrievePython.Btrieve_INDEX_97
    INDEX_98 = _btrievePython.Btrieve_INDEX_98
    INDEX_99 = _btrievePython.Btrieve_INDEX_99
    INDEX_100 = _btrievePython.Btrieve_INDEX_100
    INDEX_101 = _btrievePython.Btrieve_INDEX_101
    INDEX_102 = _btrievePython.Btrieve_INDEX_102
    INDEX_103 = _btrievePython.Btrieve_INDEX_103
    INDEX_104 = _btrievePython.Btrieve_INDEX_104
    INDEX_105 = _btrievePython.Btrieve_INDEX_105
    INDEX_106 = _btrievePython.Btrieve_INDEX_106
    INDEX_107 = _btrievePython.Btrieve_INDEX_107
    INDEX_108 = _btrievePython.Btrieve_INDEX_108
    INDEX_109 = _btrievePython.Btrieve_INDEX_109
    INDEX_110 = _btrievePython.Btrieve_INDEX_110
    INDEX_111 = _btrievePython.Btrieve_INDEX_111
    INDEX_112 = _btrievePython.Btrieve_INDEX_112
    INDEX_113 = _btrievePython.Btrieve_INDEX_113
    INDEX_114 = _btrievePython.Btrieve_INDEX_114
    INDEX_115 = _btrievePython.Btrieve_INDEX_115
    INDEX_116 = _btrievePython.Btrieve_INDEX_116
    INDEX_117 = _btrievePython.Btrieve_INDEX_117
    INDEX_118 = _btrievePython.Btrieve_INDEX_118
    INDEX_119 = _btrievePython.Btrieve_INDEX_119
    INDEX_SYSTEM = _btrievePython.Btrieve_INDEX_SYSTEM
    INDEX_NONE = _btrievePython.Btrieve_INDEX_NONE
    INDEX_UNKNOWN = _btrievePython.Btrieve_INDEX_UNKNOWN
    LOCATION_MODE_NO_PREFERENCE = _btrievePython.Btrieve_LOCATION_MODE_NO_PREFERENCE
    LOCATION_MODE_FORCE_LOCAL = _btrievePython.Btrieve_LOCATION_MODE_FORCE_LOCAL
    LOCATION_MODE_FORCE_REMOTE = _btrievePython.Btrieve_LOCATION_MODE_FORCE_REMOTE
    LOCATION_MODE_UNKNOWN = _btrievePython.Btrieve_LOCATION_MODE_UNKNOWN
    LOCK_MODE_NONE = _btrievePython.Btrieve_LOCK_MODE_NONE
    LOCK_MODE_SINGLE_WAIT = _btrievePython.Btrieve_LOCK_MODE_SINGLE_WAIT
    LOCK_MODE_SINGLE_NO_WAIT = _btrievePython.Btrieve_LOCK_MODE_SINGLE_NO_WAIT
    LOCK_MODE_MULTIPLE_WAIT = _btrievePython.Btrieve_LOCK_MODE_MULTIPLE_WAIT
    LOCK_MODE_MULTIPLE_NO_WAIT = _btrievePython.Btrieve_LOCK_MODE_MULTIPLE_NO_WAIT
    LOCK_MODE_UNKNOWN = _btrievePython.Btrieve_LOCK_MODE_UNKNOWN
    NULL_KEY_MODE_NONE = _btrievePython.Btrieve_NULL_KEY_MODE_NONE
    NULL_KEY_MODE_ALL_SEGMENTS = _btrievePython.Btrieve_NULL_KEY_MODE_ALL_SEGMENTS
    NULL_KEY_MODE_ANY_SEGMENTS = _btrievePython.Btrieve_NULL_KEY_MODE_ANY_SEGMENTS
    NULL_KEY_MODE_UNKNOWN = _btrievePython.Btrieve_NULL_KEY_MODE_UNKNOWN
    OPEN_MODE_NORMAL = _btrievePython.Btrieve_OPEN_MODE_NORMAL
    OPEN_MODE_ACCELERATED = _btrievePython.Btrieve_OPEN_MODE_ACCELERATED
    OPEN_MODE_READ_ONLY = _btrievePython.Btrieve_OPEN_MODE_READ_ONLY
    OPEN_MODE_EXCLUSIVE = _btrievePython.Btrieve_OPEN_MODE_EXCLUSIVE
    OPEN_MODE_UNKNOWN = _btrievePython.Btrieve_OPEN_MODE_UNKNOWN
    OWNER_MODE_NONE = _btrievePython.Btrieve_OWNER_MODE_NONE
    OWNER_MODE_NO_ENCRYPTION_NO_READ_ALLOWED = _btrievePython.Btrieve_OWNER_MODE_NO_ENCRYPTION_NO_READ_ALLOWED
    OWNER_MODE_NO_ENCRYPTION_READ_ALLOWED = _btrievePython.Btrieve_OWNER_MODE_NO_ENCRYPTION_READ_ALLOWED
    OWNER_MODE_ENCRYPTION_NO_READ_ALLOWED = _btrievePython.Btrieve_OWNER_MODE_ENCRYPTION_NO_READ_ALLOWED
    OWNER_MODE_ENCRYPTION_READ_ALLOWED = _btrievePython.Btrieve_OWNER_MODE_ENCRYPTION_READ_ALLOWED
    OWNER_MODE_UNKNOWN = _btrievePython.Btrieve_OWNER_MODE_UNKNOWN
    PAGE_LOCK_TYPE_NONE = _btrievePython.Btrieve_PAGE_LOCK_TYPE_NONE
    PAGE_LOCK_TYPE_DATA_PAGE = _btrievePython.Btrieve_PAGE_LOCK_TYPE_DATA_PAGE
    PAGE_LOCK_TYPE_INDEX_PAGE = _btrievePython.Btrieve_PAGE_LOCK_TYPE_INDEX_PAGE
    PAGE_LOCK_TYPE_VARIABLE_PAGE = _btrievePython.Btrieve_PAGE_LOCK_TYPE_VARIABLE_PAGE
    PAGE_LOCK_TYPE_UNKNOWN = _btrievePython.Btrieve_PAGE_LOCK_TYPE_UNKNOWN
    PAGE_SIZE_512 = _btrievePython.Btrieve_PAGE_SIZE_512
    PAGE_SIZE_1024 = _btrievePython.Btrieve_PAGE_SIZE_1024
    PAGE_SIZE_1536 = _btrievePython.Btrieve_PAGE_SIZE_1536
    PAGE_SIZE_2048 = _btrievePython.Btrieve_PAGE_SIZE_2048
    PAGE_SIZE_3072 = _btrievePython.Btrieve_PAGE_SIZE_3072
    PAGE_SIZE_3584 = _btrievePython.Btrieve_PAGE_SIZE_3584
    PAGE_SIZE_4096 = _btrievePython.Btrieve_PAGE_SIZE_4096
    PAGE_SIZE_8192 = _btrievePython.Btrieve_PAGE_SIZE_8192
    PAGE_SIZE_16384 = _btrievePython.Btrieve_PAGE_SIZE_16384
    PAGE_SIZE_DEFAULT = _btrievePython.Btrieve_PAGE_SIZE_DEFAULT
    PAGE_SIZE_UNKNOWN = _btrievePython.Btrieve_PAGE_SIZE_UNKNOWN
    RECORD_COMPRESSION_MODE_NONE = _btrievePython.Btrieve_RECORD_COMPRESSION_MODE_NONE
    RECORD_COMPRESSION_MODE_BLANK_TRUNCATION = _btrievePython.Btrieve_RECORD_COMPRESSION_MODE_BLANK_TRUNCATION
    RECORD_COMPRESSION_MODE_RUN_LENGTH_ENCODING = _btrievePython.Btrieve_RECORD_COMPRESSION_MODE_RUN_LENGTH_ENCODING
    RECORD_COMPRESSION_MODE_UNKNOWN = _btrievePython.Btrieve_RECORD_COMPRESSION_MODE_UNKNOWN
    STATUS_CODE_NO_ERROR = _btrievePython.Btrieve_STATUS_CODE_NO_ERROR
    STATUS_CODE_INVALID_FUNCTION = _btrievePython.Btrieve_STATUS_CODE_INVALID_FUNCTION
    STATUS_CODE_IO_ERROR = _btrievePython.Btrieve_STATUS_CODE_IO_ERROR
    STATUS_CODE_FILE_NOT_OPEN = _btrievePython.Btrieve_STATUS_CODE_FILE_NOT_OPEN
    STATUS_CODE_KEY_VALUE_NOT_FOUND = _btrievePython.Btrieve_STATUS_CODE_KEY_VALUE_NOT_FOUND
    STATUS_CODE_DUPLICATE_KEY_VALUE = _btrievePython.Btrieve_STATUS_CODE_DUPLICATE_KEY_VALUE
    STATUS_CODE_INVALID_INDEX_NUMBER = _btrievePython.Btrieve_STATUS_CODE_INVALID_INDEX_NUMBER
    STATUS_CODE_DIFFERENT_INDEX_NUMBER = _btrievePython.Btrieve_STATUS_CODE_DIFFERENT_INDEX_NUMBER
    STATUS_CODE_POSITION_NOT_SET = _btrievePython.Btrieve_STATUS_CODE_POSITION_NOT_SET
    STATUS_CODE_END_OF_FILE = _btrievePython.Btrieve_STATUS_CODE_END_OF_FILE
    STATUS_CODE_MODIFIABLE_KEYVALUE_ERROR = _btrievePython.Btrieve_STATUS_CODE_MODIFIABLE_KEYVALUE_ERROR
    STATUS_CODE_FILENAME_BAD = _btrievePython.Btrieve_STATUS_CODE_FILENAME_BAD
    STATUS_CODE_FILE_NOT_FOUND = _btrievePython.Btrieve_STATUS_CODE_FILE_NOT_FOUND
    STATUS_CODE_EXTENDED_FILE_ERROR = _btrievePython.Btrieve_STATUS_CODE_EXTENDED_FILE_ERROR
    STATUS_CODE_PREIMAGE_OPEN_ERROR = _btrievePython.Btrieve_STATUS_CODE_PREIMAGE_OPEN_ERROR
    STATUS_CODE_PREIMAGE_IO_ERROR = _btrievePython.Btrieve_STATUS_CODE_PREIMAGE_IO_ERROR
    STATUS_CODE_EXPANSION_ERROR = _btrievePython.Btrieve_STATUS_CODE_EXPANSION_ERROR
    STATUS_CODE_CLOSE_ERROR = _btrievePython.Btrieve_STATUS_CODE_CLOSE_ERROR
    STATUS_CODE_DISKFULL = _btrievePython.Btrieve_STATUS_CODE_DISKFULL
    STATUS_CODE_UNRECOVERABLE_ERROR = _btrievePython.Btrieve_STATUS_CODE_UNRECOVERABLE_ERROR
    STATUS_CODE_RECORD_MANAGER_INACTIVE = _btrievePython.Btrieve_STATUS_CODE_RECORD_MANAGER_INACTIVE
    STATUS_CODE_KEYBUFFER_TOO_SHORT = _btrievePython.Btrieve_STATUS_CODE_KEYBUFFER_TOO_SHORT
    STATUS_CODE_DATALENGTH_ERROR = _btrievePython.Btrieve_STATUS_CODE_DATALENGTH_ERROR
    STATUS_CODE_POSITIONBLOCK_LENGTH = _btrievePython.Btrieve_STATUS_CODE_POSITIONBLOCK_LENGTH
    STATUS_CODE_PAGE_SIZE_ERROR = _btrievePython.Btrieve_STATUS_CODE_PAGE_SIZE_ERROR
    STATUS_CODE_CREATE_IO_ERROR = _btrievePython.Btrieve_STATUS_CODE_CREATE_IO_ERROR
    STATUS_CODE_NUMBER_OF_INDEXES = _btrievePython.Btrieve_STATUS_CODE_NUMBER_OF_INDEXES
    STATUS_CODE_INVALID_KEY_POSITION = _btrievePython.Btrieve_STATUS_CODE_INVALID_KEY_POSITION
    STATUS_CODE_INVALID_RECORD_LENGTH = _btrievePython.Btrieve_STATUS_CODE_INVALID_RECORD_LENGTH
    STATUS_CODE_INVALID_KEYLENGTH = _btrievePython.Btrieve_STATUS_CODE_INVALID_KEYLENGTH
    STATUS_CODE_NOT_A_BTRIEVE_FILE = _btrievePython.Btrieve_STATUS_CODE_NOT_A_BTRIEVE_FILE
    STATUS_CODE_FILE_ALREADY_EXTENDED = _btrievePython.Btrieve_STATUS_CODE_FILE_ALREADY_EXTENDED
    STATUS_CODE_EXTEND_IO_ERROR = _btrievePython.Btrieve_STATUS_CODE_EXTEND_IO_ERROR
    STATUS_CODE_BTR_CANNOT_UNLOAD = _btrievePython.Btrieve_STATUS_CODE_BTR_CANNOT_UNLOAD
    STATUS_CODE_INVALID_EXTENSION_NAME = _btrievePython.Btrieve_STATUS_CODE_INVALID_EXTENSION_NAME
    STATUS_CODE_DIRECTORY_ERROR = _btrievePython.Btrieve_STATUS_CODE_DIRECTORY_ERROR
    STATUS_CODE_TRANSACTION_ERROR = _btrievePython.Btrieve_STATUS_CODE_TRANSACTION_ERROR
    STATUS_CODE_TRANSACTION_IS_ACTIVE = _btrievePython.Btrieve_STATUS_CODE_TRANSACTION_IS_ACTIVE
    STATUS_CODE_TRANSACTION_FILE_IO_ERROR = _btrievePython.Btrieve_STATUS_CODE_TRANSACTION_FILE_IO_ERROR
    STATUS_CODE_END_TRANSACTION_ERROR = _btrievePython.Btrieve_STATUS_CODE_END_TRANSACTION_ERROR
    STATUS_CODE_TRANSACTION_MAX_FILES = _btrievePython.Btrieve_STATUS_CODE_TRANSACTION_MAX_FILES
    STATUS_CODE_OPERATION_NOT_ALLOWED = _btrievePython.Btrieve_STATUS_CODE_OPERATION_NOT_ALLOWED
    STATUS_CODE_INCOMPLETE_ACCEL_ACCESS = _btrievePython.Btrieve_STATUS_CODE_INCOMPLETE_ACCEL_ACCESS
    STATUS_CODE_INVALID_RECORD_ADDRESS = _btrievePython.Btrieve_STATUS_CODE_INVALID_RECORD_ADDRESS
    STATUS_CODE_NULL_KEYPATH = _btrievePython.Btrieve_STATUS_CODE_NULL_KEYPATH
    STATUS_CODE_INCONSISTENT_KEY_FLAGS = _btrievePython.Btrieve_STATUS_CODE_INCONSISTENT_KEY_FLAGS
    STATUS_CODE_ACCESS_TO_FILE_DENIED = _btrievePython.Btrieve_STATUS_CODE_ACCESS_TO_FILE_DENIED
    STATUS_CODE_MAXIMUM_OPEN_FILES = _btrievePython.Btrieve_STATUS_CODE_MAXIMUM_OPEN_FILES
    STATUS_CODE_INVALID_ALT_SEQUENCE_DEF = _btrievePython.Btrieve_STATUS_CODE_INVALID_ALT_SEQUENCE_DEF
    STATUS_CODE_KEY_TYPE_ERROR = _btrievePython.Btrieve_STATUS_CODE_KEY_TYPE_ERROR
    STATUS_CODE_OWNER_ALREADY_SET = _btrievePython.Btrieve_STATUS_CODE_OWNER_ALREADY_SET
    STATUS_CODE_INVALID_OWNER = _btrievePython.Btrieve_STATUS_CODE_INVALID_OWNER
    STATUS_CODE_ERROR_WRITING_CACHE = _btrievePython.Btrieve_STATUS_CODE_ERROR_WRITING_CACHE
    STATUS_CODE_INVALID_INTERFACE = _btrievePython.Btrieve_STATUS_CODE_INVALID_INTERFACE
    STATUS_CODE_VARIABLE_PAGE_ERROR = _btrievePython.Btrieve_STATUS_CODE_VARIABLE_PAGE_ERROR
    STATUS_CODE_AUTOINCREMENT_ERROR = _btrievePython.Btrieve_STATUS_CODE_AUTOINCREMENT_ERROR
    STATUS_CODE_INCOMPLETE_INDEX = _btrievePython.Btrieve_STATUS_CODE_INCOMPLETE_INDEX
    STATUS_CODE_EXPANED_MEM_ERROR = _btrievePython.Btrieve_STATUS_CODE_EXPANED_MEM_ERROR
    STATUS_CODE_COMPRESS_BUFFER_TOO_SHORT = _btrievePython.Btrieve_STATUS_CODE_COMPRESS_BUFFER_TOO_SHORT
    STATUS_CODE_FILE_ALREADY_EXISTS = _btrievePython.Btrieve_STATUS_CODE_FILE_ALREADY_EXISTS
    STATUS_CODE_REJECT_COUNT_REACHED = _btrievePython.Btrieve_STATUS_CODE_REJECT_COUNT_REACHED
    STATUS_CODE_SMALL_EX_GET_BUFFER_ERROR = _btrievePython.Btrieve_STATUS_CODE_SMALL_EX_GET_BUFFER_ERROR
    STATUS_CODE_INVALID_GET_EXPRESSION = _btrievePython.Btrieve_STATUS_CODE_INVALID_GET_EXPRESSION
    STATUS_CODE_INVALID_EXT_INSERT_BUFF = _btrievePython.Btrieve_STATUS_CODE_INVALID_EXT_INSERT_BUFF
    STATUS_CODE_OPTIMIZE_LIMIT_REACHED = _btrievePython.Btrieve_STATUS_CODE_OPTIMIZE_LIMIT_REACHED
    STATUS_CODE_INVALID_EXTRACTOR = _btrievePython.Btrieve_STATUS_CODE_INVALID_EXTRACTOR
    STATUS_CODE_RI_TOO_MANY_DATABASES = _btrievePython.Btrieve_STATUS_CODE_RI_TOO_MANY_DATABASES
    STATUS_CODE_RIDDF_CANNOT_OPEN = _btrievePython.Btrieve_STATUS_CODE_RIDDF_CANNOT_OPEN
    STATUS_CODE_RI_CASCADE_TOO_DEEP = _btrievePython.Btrieve_STATUS_CODE_RI_CASCADE_TOO_DEEP
    STATUS_CODE_RI_CASCADE_ERROR = _btrievePython.Btrieve_STATUS_CODE_RI_CASCADE_ERROR
    STATUS_CODE_RI_VIOLATION = _btrievePython.Btrieve_STATUS_CODE_RI_VIOLATION
    STATUS_CODE_RI_REFERENCED_FILE_CANNOT_OPEN = _btrievePython.Btrieve_STATUS_CODE_RI_REFERENCED_FILE_CANNOT_OPEN
    STATUS_CODE_RI_OUT_OF_SYNC = _btrievePython.Btrieve_STATUS_CODE_RI_OUT_OF_SYNC
    STATUS_CODE_END_CHANGED_TO_ABORT = _btrievePython.Btrieve_STATUS_CODE_END_CHANGED_TO_ABORT
    STATUS_CODE_RI_CONFLICT = _btrievePython.Btrieve_STATUS_CODE_RI_CONFLICT
    STATUS_CODE_CANT_LOOP_IN_SERVER = _btrievePython.Btrieve_STATUS_CODE_CANT_LOOP_IN_SERVER
    STATUS_CODE_DEAD_LOCK = _btrievePython.Btrieve_STATUS_CODE_DEAD_LOCK
    STATUS_CODE_PROGRAMMING_ERROR = _btrievePython.Btrieve_STATUS_CODE_PROGRAMMING_ERROR
    STATUS_CODE_CONFLICT = _btrievePython.Btrieve_STATUS_CODE_CONFLICT
    STATUS_CODE_LOCKERROR = _btrievePython.Btrieve_STATUS_CODE_LOCKERROR
    STATUS_CODE_LOST_POSITION = _btrievePython.Btrieve_STATUS_CODE_LOST_POSITION
    STATUS_CODE_READ_OUTSIDE_TRANSACTION = _btrievePython.Btrieve_STATUS_CODE_READ_OUTSIDE_TRANSACTION
    STATUS_CODE_RECORD_INUSE = _btrievePython.Btrieve_STATUS_CODE_RECORD_INUSE
    STATUS_CODE_FILE_INUSE = _btrievePython.Btrieve_STATUS_CODE_FILE_INUSE
    STATUS_CODE_FILE_TABLE_FULL = _btrievePython.Btrieve_STATUS_CODE_FILE_TABLE_FULL
    STATUS_CODE_NOHANDLES_AVAILABLE = _btrievePython.Btrieve_STATUS_CODE_NOHANDLES_AVAILABLE
    STATUS_CODE_INCOMPATIBLE_MODE_ERROR = _btrievePython.Btrieve_STATUS_CODE_INCOMPATIBLE_MODE_ERROR
    STATUS_CODE_DEVICE_TABLE_FULL = _btrievePython.Btrieve_STATUS_CODE_DEVICE_TABLE_FULL
    STATUS_CODE_SERVER_ERROR = _btrievePython.Btrieve_STATUS_CODE_SERVER_ERROR
    STATUS_CODE_TRANSACTION_TABLE_FULL = _btrievePython.Btrieve_STATUS_CODE_TRANSACTION_TABLE_FULL
    STATUS_CODE_INCOMPATIBLE_LOCK_TYPE = _btrievePython.Btrieve_STATUS_CODE_INCOMPATIBLE_LOCK_TYPE
    STATUS_CODE_PERMISSION_ERROR = _btrievePython.Btrieve_STATUS_CODE_PERMISSION_ERROR
    STATUS_CODE_SESSION_NO_LONGER_VALID = _btrievePython.Btrieve_STATUS_CODE_SESSION_NO_LONGER_VALID
    STATUS_CODE_COMMUNICATIONS_ERROR = _btrievePython.Btrieve_STATUS_CODE_COMMUNICATIONS_ERROR
    STATUS_CODE_DATA_MESSAGE_TOO_SMALL = _btrievePython.Btrieve_STATUS_CODE_DATA_MESSAGE_TOO_SMALL
    STATUS_CODE_INTERNAL_TRANSACTION_ERROR = _btrievePython.Btrieve_STATUS_CODE_INTERNAL_TRANSACTION_ERROR
    STATUS_CODE_REQUESTER_CANT_ACCESS_RUNTIME = _btrievePython.Btrieve_STATUS_CODE_REQUESTER_CANT_ACCESS_RUNTIME
    STATUS_CODE_NO_CACHE_BUFFERS_AVAIL = _btrievePython.Btrieve_STATUS_CODE_NO_CACHE_BUFFERS_AVAIL
    STATUS_CODE_NO_OS_MEMORY_AVAIL = _btrievePython.Btrieve_STATUS_CODE_NO_OS_MEMORY_AVAIL
    STATUS_CODE_NO_STACK_AVAIL = _btrievePython.Btrieve_STATUS_CODE_NO_STACK_AVAIL
    STATUS_CODE_CHUNK_OFFSET_TOO_LONG = _btrievePython.Btrieve_STATUS_CODE_CHUNK_OFFSET_TOO_LONG
    STATUS_CODE_LOCALE_ERROR = _btrievePython.Btrieve_STATUS_CODE_LOCALE_ERROR
    STATUS_CODE_CANNOT_CREATE_WITH_VAT = _btrievePython.Btrieve_STATUS_CODE_CANNOT_CREATE_WITH_VAT
    STATUS_CODE_CHUNK_CANNOT_GET_NEXT = _btrievePython.Btrieve_STATUS_CODE_CHUNK_CANNOT_GET_NEXT
    STATUS_CODE_CHUNK_INCOMPATIBLE_FILE = _btrievePython.Btrieve_STATUS_CODE_CHUNK_INCOMPATIBLE_FILE
    STATUS_CODE_TRANSACTION_TOO_COMPLEX = _btrievePython.Btrieve_STATUS_CODE_TRANSACTION_TOO_COMPLEX
    STATUS_CODE_ARCH_BLOG_OPEN_ERROR = _btrievePython.Btrieve_STATUS_CODE_ARCH_BLOG_OPEN_ERROR
    STATUS_CODE_ARCH_FILE_NOT_LOGGED = _btrievePython.Btrieve_STATUS_CODE_ARCH_FILE_NOT_LOGGED
    STATUS_CODE_ARCH_FILE_IN_USE = _btrievePython.Btrieve_STATUS_CODE_ARCH_FILE_IN_USE
    STATUS_CODE_ARCH_LOGFILE_NOT_FOUND = _btrievePython.Btrieve_STATUS_CODE_ARCH_LOGFILE_NOT_FOUND
    STATUS_CODE_ARCH_LOGFILE_INVALID = _btrievePython.Btrieve_STATUS_CODE_ARCH_LOGFILE_INVALID
    STATUS_CODE_ARCH_DUMPFILE_ACCESS_ERROR = _btrievePython.Btrieve_STATUS_CODE_ARCH_DUMPFILE_ACCESS_ERROR
    STATUS_CODE_LOCATOR_FILE_INDICATOR = _btrievePython.Btrieve_STATUS_CODE_LOCATOR_FILE_INDICATOR
    STATUS_CODE_NO_SYSTEM_LOCKS_AVAILABLE = _btrievePython.Btrieve_STATUS_CODE_NO_SYSTEM_LOCKS_AVAILABLE
    STATUS_CODE_FILE_FULL = _btrievePython.Btrieve_STATUS_CODE_FILE_FULL
    STATUS_CODE_MORE_THAN_5_CONCURRENT_USERS = _btrievePython.Btrieve_STATUS_CODE_MORE_THAN_5_CONCURRENT_USERS
    STATUS_CODE_ISR_NOT_FOUND = _btrievePython.Btrieve_STATUS_CODE_ISR_NOT_FOUND
    STATUS_CODE_ISR_INVALID = _btrievePython.Btrieve_STATUS_CODE_ISR_INVALID
    STATUS_CODE_ACS_NOT_FOUND = _btrievePython.Btrieve_STATUS_CODE_ACS_NOT_FOUND
    STATUS_CODE_CANNOT_CONVERT_RP = _btrievePython.Btrieve_STATUS_CODE_CANNOT_CONVERT_RP
    STATUS_CODE_INVALID_NULL_INDICATOR = _btrievePython.Btrieve_STATUS_CODE_INVALID_NULL_INDICATOR
    STATUS_CODE_INVALID_KEY_OPTION = _btrievePython.Btrieve_STATUS_CODE_INVALID_KEY_OPTION
    STATUS_CODE_INCOMPATIBLE_CLOSE = _btrievePython.Btrieve_STATUS_CODE_INCOMPATIBLE_CLOSE
    STATUS_CODE_INVALID_USERNAME = _btrievePython.Btrieve_STATUS_CODE_INVALID_USERNAME
    STATUS_CODE_INVALID_DATABASE = _btrievePython.Btrieve_STATUS_CODE_INVALID_DATABASE
    STATUS_CODE_NO_SSQL_RIGHTS = _btrievePython.Btrieve_STATUS_CODE_NO_SSQL_RIGHTS
    STATUS_CODE_ALREADY_LOGGED_IN = _btrievePython.Btrieve_STATUS_CODE_ALREADY_LOGGED_IN
    STATUS_CODE_NO_DATABASE_SERVICES = _btrievePython.Btrieve_STATUS_CODE_NO_DATABASE_SERVICES
    STATUS_CODE_DUPLICATE_SYSTEM_KEY = _btrievePython.Btrieve_STATUS_CODE_DUPLICATE_SYSTEM_KEY
    STATUS_CODE_LOG_SEGMENT_MISSING = _btrievePython.Btrieve_STATUS_CODE_LOG_SEGMENT_MISSING
    STATUS_CODE_ROLL_FORWARD_ERROR = _btrievePython.Btrieve_STATUS_CODE_ROLL_FORWARD_ERROR
    STATUS_CODE_SYSTEM_KEY_INTERNAL = _btrievePython.Btrieve_STATUS_CODE_SYSTEM_KEY_INTERNAL
    STATUS_CODE_DBS_INTERNAL_ERROR = _btrievePython.Btrieve_STATUS_CODE_DBS_INTERNAL_ERROR
    STATUS_CODE_NESTING_DEPTH_ERROR = _btrievePython.Btrieve_STATUS_CODE_NESTING_DEPTH_ERROR
    STATUS_CODE_INVALID_PARAMETER_TO_MKDE = _btrievePython.Btrieve_STATUS_CODE_INVALID_PARAMETER_TO_MKDE
    STATUS_CODE_USER_COUNT_LIMIT_EXCEEDED = _btrievePython.Btrieve_STATUS_CODE_USER_COUNT_LIMIT_EXCEEDED
    STATUS_CODE_CLIENT_TABLE_FULL = _btrievePython.Btrieve_STATUS_CODE_CLIENT_TABLE_FULL
    STATUS_CODE_LAST_SEGMENT_ERROR = _btrievePython.Btrieve_STATUS_CODE_LAST_SEGMENT_ERROR
    STATUS_CODE_LOGIN_FAILED_BAD_USERNAME = _btrievePython.Btrieve_STATUS_CODE_LOGIN_FAILED_BAD_USERNAME
    STATUS_CODE_LOGIN_FAILED_BAD_PASSWORD = _btrievePython.Btrieve_STATUS_CODE_LOGIN_FAILED_BAD_PASSWORD
    STATUS_CODE_LOGIN_FAILED_BAD_DATABASE = _btrievePython.Btrieve_STATUS_CODE_LOGIN_FAILED_BAD_DATABASE
    STATUS_CODE_LOGIN_ALREADY_LOGGED_IN = _btrievePython.Btrieve_STATUS_CODE_LOGIN_ALREADY_LOGGED_IN
    STATUS_CODE_LOGIN_LOGOUT_FAILED = _btrievePython.Btrieve_STATUS_CODE_LOGIN_LOGOUT_FAILED
    STATUS_CODE_LOGIN_WRONG_URI_FORMAT = _btrievePython.Btrieve_STATUS_CODE_LOGIN_WRONG_URI_FORMAT
    STATUS_CODE_LOGIN_FILE_AND_TABLE_NOT_FOUND = _btrievePython.Btrieve_STATUS_CODE_LOGIN_FILE_AND_TABLE_NOT_FOUND
    STATUS_CODE_LOGIN_TABLE_NOT_IN_DATABASE = _btrievePython.Btrieve_STATUS_CODE_LOGIN_TABLE_NOT_IN_DATABASE
    STATUS_CODE_LOGIN_DIRECTORY_NOT_IN_DATABASE = _btrievePython.Btrieve_STATUS_CODE_LOGIN_DIRECTORY_NOT_IN_DATABASE
    STATUS_CODE_LOCK_PARM_OUTOFRANGE = _btrievePython.Btrieve_STATUS_CODE_LOCK_PARM_OUTOFRANGE
    STATUS_CODE_MEM_ALLOCATION_ERR = _btrievePython.Btrieve_STATUS_CODE_MEM_ALLOCATION_ERR
    STATUS_CODE_MEM_PARM_TOO_SMALL = _btrievePython.Btrieve_STATUS_CODE_MEM_PARM_TOO_SMALL
    STATUS_CODE_PAGE_SIZE_PARM_OUTOFRANGE = _btrievePython.Btrieve_STATUS_CODE_PAGE_SIZE_PARM_OUTOFRANGE
    STATUS_CODE_INVALID_PREIMAGE_PARM = _btrievePython.Btrieve_STATUS_CODE_INVALID_PREIMAGE_PARM
    STATUS_CODE_PREIMAGE_BUF_PARM_OUTOFRANGE = _btrievePython.Btrieve_STATUS_CODE_PREIMAGE_BUF_PARM_OUTOFRANGE
    STATUS_CODE_FILES_PARM_OUTOFRANGE = _btrievePython.Btrieve_STATUS_CODE_FILES_PARM_OUTOFRANGE
    STATUS_CODE_INVALID_INIT_PARM = _btrievePython.Btrieve_STATUS_CODE_INVALID_INIT_PARM
    STATUS_CODE_INVALID_TRANS_PARM = _btrievePython.Btrieve_STATUS_CODE_INVALID_TRANS_PARM
    STATUS_CODE_ERROR_ACC_TRANS_CONTROL_FILE = _btrievePython.Btrieve_STATUS_CODE_ERROR_ACC_TRANS_CONTROL_FILE
    STATUS_CODE_COMPRESSION_BUF_PARM_OUTOFRANGE = _btrievePython.Btrieve_STATUS_CODE_COMPRESSION_BUF_PARM_OUTOFRANGE
    STATUS_CODE_INV_N_OPTION = _btrievePython.Btrieve_STATUS_CODE_INV_N_OPTION
    STATUS_CODE_TASK_LIST_FULL = _btrievePython.Btrieve_STATUS_CODE_TASK_LIST_FULL
    STATUS_CODE_STOP_WARNING = _btrievePython.Btrieve_STATUS_CODE_STOP_WARNING
    STATUS_CODE_POINTER_PARM_INVALID = _btrievePython.Btrieve_STATUS_CODE_POINTER_PARM_INVALID
    STATUS_CODE_ALREADY_INITIALIZED = _btrievePython.Btrieve_STATUS_CODE_ALREADY_INITIALIZED
    STATUS_CODE_REQ_CANT_FIND_RES_DLL = _btrievePython.Btrieve_STATUS_CODE_REQ_CANT_FIND_RES_DLL
    STATUS_CODE_ALREADY_INSIDE_BTR_FUNCTION = _btrievePython.Btrieve_STATUS_CODE_ALREADY_INSIDE_BTR_FUNCTION
    STATUS_CODE_CALLBACK_ABORT = _btrievePython.Btrieve_STATUS_CODE_CALLBACK_ABORT
    STATUS_CODE_INTF_COMM_ERROR = _btrievePython.Btrieve_STATUS_CODE_INTF_COMM_ERROR
    STATUS_CODE_FAILED_TO_INITIALIZE = _btrievePython.Btrieve_STATUS_CODE_FAILED_TO_INITIALIZE
    STATUS_CODE_MKDE_SHUTTING_DOWN = _btrievePython.Btrieve_STATUS_CODE_MKDE_SHUTTING_DOWN
    STATUS_CODE_INTERNAL_ERROR = _btrievePython.Btrieve_STATUS_CODE_INTERNAL_ERROR
    STATUS_CODE_INSUFFICIENT_MEM_ALLOC = _btrievePython.Btrieve_STATUS_CODE_INSUFFICIENT_MEM_ALLOC
    STATUS_CODE_INVALID_OPTION = _btrievePython.Btrieve_STATUS_CODE_INVALID_OPTION
    STATUS_CODE_NO_LOCAL_ACCESS_ALLOWED = _btrievePython.Btrieve_STATUS_CODE_NO_LOCAL_ACCESS_ALLOWED
    STATUS_CODE_SPX_NOT_INSTALLED = _btrievePython.Btrieve_STATUS_CODE_SPX_NOT_INSTALLED
    STATUS_CODE_INCORRECT_SPX_VERSION = _btrievePython.Btrieve_STATUS_CODE_INCORRECT_SPX_VERSION
    STATUS_CODE_NO_AVAIL_SPX_CONNECTION = _btrievePython.Btrieve_STATUS_CODE_NO_AVAIL_SPX_CONNECTION
    STATUS_CODE_INVALID_PTR_PARM = _btrievePython.Btrieve_STATUS_CODE_INVALID_PTR_PARM
    STATUS_CODE_CANT_CONNECT_TO_615 = _btrievePython.Btrieve_STATUS_CODE_CANT_CONNECT_TO_615
    STATUS_CODE_CANT_LOAD_MKDE_ROUTER = _btrievePython.Btrieve_STATUS_CODE_CANT_LOAD_MKDE_ROUTER
    STATUS_CODE_UT_THUNK_NOT_LOADED = _btrievePython.Btrieve_STATUS_CODE_UT_THUNK_NOT_LOADED
    STATUS_CODE_NO_RESOURCE_DLL = _btrievePython.Btrieve_STATUS_CODE_NO_RESOURCE_DLL
    STATUS_CODE_OS_ERROR = _btrievePython.Btrieve_STATUS_CODE_OS_ERROR
    STATUS_CODE_MK_ROUTER_MEM_ERROR = _btrievePython.Btrieve_STATUS_CODE_MK_ROUTER_MEM_ERROR
    STATUS_CODE_MK_NO_LOCAL_ACCESS_ALLOWED = _btrievePython.Btrieve_STATUS_CODE_MK_NO_LOCAL_ACCESS_ALLOWED
    STATUS_CODE_MK_NO_RESOURCE_DLL = _btrievePython.Btrieve_STATUS_CODE_MK_NO_RESOURCE_DLL
    STATUS_CODE_MK_INCOMPAT_COMPONENT = _btrievePython.Btrieve_STATUS_CODE_MK_INCOMPAT_COMPONENT
    STATUS_CODE_MK_TIMEOUT_ERROR = _btrievePython.Btrieve_STATUS_CODE_MK_TIMEOUT_ERROR
    STATUS_CODE_MK_OS_ERROR = _btrievePython.Btrieve_STATUS_CODE_MK_OS_ERROR
    STATUS_CODE_MK_INVALID_SESSION = _btrievePython.Btrieve_STATUS_CODE_MK_INVALID_SESSION
    STATUS_CODE_MK_SERVER_NOT_FOUND = _btrievePython.Btrieve_STATUS_CODE_MK_SERVER_NOT_FOUND
    STATUS_CODE_MK_INVALID_CONFIG = _btrievePython.Btrieve_STATUS_CODE_MK_INVALID_CONFIG
    STATUS_CODE_MK_NETAPI_NOT_LOADED = _btrievePython.Btrieve_STATUS_CODE_MK_NETAPI_NOT_LOADED
    STATUS_CODE_MK_NWAPI_NOT_LOADED = _btrievePython.Btrieve_STATUS_CODE_MK_NWAPI_NOT_LOADED
    STATUS_CODE_MK_THUNK_NOT_LOADED = _btrievePython.Btrieve_STATUS_CODE_MK_THUNK_NOT_LOADED
    STATUS_CODE_MK_LOCAL_NOT_LOADED = _btrievePython.Btrieve_STATUS_CODE_MK_LOCAL_NOT_LOADED
    STATUS_CODE_MK_PNSL_NOT_LOADED = _btrievePython.Btrieve_STATUS_CODE_MK_PNSL_NOT_LOADED
    STATUS_CODE_MK_CANT_FIND_ENGINE = _btrievePython.Btrieve_STATUS_CODE_MK_CANT_FIND_ENGINE
    STATUS_CODE_MK_INIT_ERROR = _btrievePython.Btrieve_STATUS_CODE_MK_INIT_ERROR
    STATUS_CODE_MK_INTERNAL_ERROR = _btrievePython.Btrieve_STATUS_CODE_MK_INTERNAL_ERROR
    STATUS_CODE_MK_LOCAL_MKDE_DATABUF_TOO_SMALL = _btrievePython.Btrieve_STATUS_CODE_MK_LOCAL_MKDE_DATABUF_TOO_SMALL
    STATUS_CODE_MK_CLOSED_ERROR = _btrievePython.Btrieve_STATUS_CODE_MK_CLOSED_ERROR
    STATUS_CODE_MK_SEMAPHORE_ERROR = _btrievePython.Btrieve_STATUS_CODE_MK_SEMAPHORE_ERROR
    STATUS_CODE_MK_LOADING_ERROR = _btrievePython.Btrieve_STATUS_CODE_MK_LOADING_ERROR
    STATUS_CODE_MK_BAD_SRB_FORMAT = _btrievePython.Btrieve_STATUS_CODE_MK_BAD_SRB_FORMAT
    STATUS_CODE_MK_DATABUF_LEN_TOO_LARGE = _btrievePython.Btrieve_STATUS_CODE_MK_DATABUF_LEN_TOO_LARGE
    STATUS_CODE_MK_TASK_TABLE_FULL = _btrievePython.Btrieve_STATUS_CODE_MK_TASK_TABLE_FULL
    STATUS_CODE_MK_INVALID_OP_ON_REMOTE = _btrievePython.Btrieve_STATUS_CODE_MK_INVALID_OP_ON_REMOTE
    STATUS_CODE_MK_PIDS_NOT_LOADED = _btrievePython.Btrieve_STATUS_CODE_MK_PIDS_NOT_LOADED
    STATUS_CODE_MK_BAD_PIDS = _btrievePython.Btrieve_STATUS_CODE_MK_BAD_PIDS
    STATUS_CODE_MK_IDS_CONNECT_FAILURE = _btrievePython.Btrieve_STATUS_CODE_MK_IDS_CONNECT_FAILURE
    STATUS_CODE_MK_IDS_LOGIN_FAILURE = _btrievePython.Btrieve_STATUS_CODE_MK_IDS_LOGIN_FAILURE
    STATUS_CODE_NL_FAILURE = _btrievePython.Btrieve_STATUS_CODE_NL_FAILURE
    STATUS_CODE_NL_NOT_INITIALIZED = _btrievePython.Btrieve_STATUS_CODE_NL_NOT_INITIALIZED
    STATUS_CODE_NL_NAME_NOT_FOUND = _btrievePython.Btrieve_STATUS_CODE_NL_NAME_NOT_FOUND
    STATUS_CODE_NL_PERMISSION_ERROR = _btrievePython.Btrieve_STATUS_CODE_NL_PERMISSION_ERROR
    STATUS_CODE_NL_NO_AVAILABLE_TRANSPORT = _btrievePython.Btrieve_STATUS_CODE_NL_NO_AVAILABLE_TRANSPORT
    STATUS_CODE_NL_CONNECTION_FAILURE = _btrievePython.Btrieve_STATUS_CODE_NL_CONNECTION_FAILURE
    STATUS_CODE_NL_OUT_OF_MEMORY = _btrievePython.Btrieve_STATUS_CODE_NL_OUT_OF_MEMORY
    STATUS_CODE_NL_INVALID_SESSION = _btrievePython.Btrieve_STATUS_CODE_NL_INVALID_SESSION
    STATUS_CODE_NL_MORE_DATA = _btrievePython.Btrieve_STATUS_CODE_NL_MORE_DATA
    STATUS_CODE_NL_NOT_CONNECTED = _btrievePython.Btrieve_STATUS_CODE_NL_NOT_CONNECTED
    STATUS_CODE_NL_SEND_FAILURE = _btrievePython.Btrieve_STATUS_CODE_NL_SEND_FAILURE
    STATUS_CODE_NL_RECEIVE_FAILURE = _btrievePython.Btrieve_STATUS_CODE_NL_RECEIVE_FAILURE
    STATUS_CODE_NL_INVALID_SERVER_TYPE = _btrievePython.Btrieve_STATUS_CODE_NL_INVALID_SERVER_TYPE
    STATUS_CODE_NL_SRT_FULL = _btrievePython.Btrieve_STATUS_CODE_NL_SRT_FULL
    STATUS_CODE_NL_TRANSPORT_FAILURE = _btrievePython.Btrieve_STATUS_CODE_NL_TRANSPORT_FAILURE
    STATUS_CODE_NL_RCV_DATA_OVERFLOW = _btrievePython.Btrieve_STATUS_CODE_NL_RCV_DATA_OVERFLOW
    STATUS_CODE_NL_CST_FULL = _btrievePython.Btrieve_STATUS_CODE_NL_CST_FULL
    STATUS_CODE_NL_INVALID_ADDRESS_FAMILY = _btrievePython.Btrieve_STATUS_CODE_NL_INVALID_ADDRESS_FAMILY
    STATUS_CODE_NL_NO_AUTH_CONTEXT_AVAILABLE = _btrievePython.Btrieve_STATUS_CODE_NL_NO_AUTH_CONTEXT_AVAILABLE
    STATUS_CODE_NL_INVALID_AUTH_TYPE = _btrievePython.Btrieve_STATUS_CODE_NL_INVALID_AUTH_TYPE
    STATUS_CODE_NL_INVALID_AUTH_OBJECT = _btrievePython.Btrieve_STATUS_CODE_NL_INVALID_AUTH_OBJECT
    STATUS_CODE_NL_AUTH_LEN_TOO_SMALL = _btrievePython.Btrieve_STATUS_CODE_NL_AUTH_LEN_TOO_SMALL
    STATUS_CODE_NL_INVALID_SESSION_LEVEL_PARM = _btrievePython.Btrieve_STATUS_CODE_NL_INVALID_SESSION_LEVEL_PARM
    STATUS_CODE_NL_TASK_TABLE_FULL = _btrievePython.Btrieve_STATUS_CODE_NL_TASK_TABLE_FULL
    STATUS_CODE_NL_NDS_NAME_RESOLUTION_ERROR = _btrievePython.Btrieve_STATUS_CODE_NL_NDS_NAME_RESOLUTION_ERROR
    STATUS_CODE_NL_FILE_NAME_RESOLUTION_ERROR = _btrievePython.Btrieve_STATUS_CODE_NL_FILE_NAME_RESOLUTION_ERROR
    STATUS_CODE_NL_IDS_SEND_FAILURE = _btrievePython.Btrieve_STATUS_CODE_NL_IDS_SEND_FAILURE
    STATUS_CODE_NL_IDS_RCV_FAILURE = _btrievePython.Btrieve_STATUS_CODE_NL_IDS_RCV_FAILURE
    STATUS_CODE_UNKNOWN = _btrievePython.Btrieve_STATUS_CODE_UNKNOWN
    SYSTEM_DATA_MODE_YES = _btrievePython.Btrieve_SYSTEM_DATA_MODE_YES
    SYSTEM_DATA_MODE_NO = _btrievePython.Btrieve_SYSTEM_DATA_MODE_NO
    SYSTEM_DATA_MODE_DEFAULT = _btrievePython.Btrieve_SYSTEM_DATA_MODE_DEFAULT
    SYSTEM_DATA_MODE_UNKNOWN = _btrievePython.Btrieve_SYSTEM_DATA_MODE_UNKNOWN
    TRANSACTION_MODE_EXCLUSIVE = _btrievePython.Btrieve_TRANSACTION_MODE_EXCLUSIVE
    TRANSACTION_MODE_CONCURRENT_WRITE_WAIT = _btrievePython.Btrieve_TRANSACTION_MODE_CONCURRENT_WRITE_WAIT
    TRANSACTION_MODE_CONCURRENT_NO_WRITE_WAIT = _btrievePython.Btrieve_TRANSACTION_MODE_CONCURRENT_NO_WRITE_WAIT
    TRANSACTION_MODE_UNKNOWN = _btrievePython.Btrieve_TRANSACTION_MODE_UNKNOWN
    UNLOCK_MODE_SINGLE = _btrievePython.Btrieve_UNLOCK_MODE_SINGLE
    UNLOCK_MODE_MULTIPLE = _btrievePython.Btrieve_UNLOCK_MODE_MULTIPLE
    UNLOCK_MODE_UNKNOWN = _btrievePython.Btrieve_UNLOCK_MODE_UNKNOWN
    VARIABLE_LENGTH_RECORDS_MODE_NO = _btrievePython.Btrieve_VARIABLE_LENGTH_RECORDS_MODE_NO
    VARIABLE_LENGTH_RECORDS_MODE_YES = _btrievePython.Btrieve_VARIABLE_LENGTH_RECORDS_MODE_YES
    VARIABLE_LENGTH_RECORDS_MODE_YES_VARIABLE_ALLOCATION_TAILS = _btrievePython.Btrieve_VARIABLE_LENGTH_RECORDS_MODE_YES_VARIABLE_ALLOCATION_TAILS
    VARIABLE_LENGTH_RECORDS_MODE_UNKNOWN = _btrievePython.Btrieve_VARIABLE_LENGTH_RECORDS_MODE_UNKNOWN
    VERSION_TYPE_NONE = _btrievePython.Btrieve_VERSION_TYPE_NONE
    VERSION_TYPE_BTRIEVE_ENGINE = _btrievePython.Btrieve_VERSION_TYPE_BTRIEVE_ENGINE
    VERSION_TYPE_WORKGROUP_ENGINE = _btrievePython.Btrieve_VERSION_TYPE_WORKGROUP_ENGINE
    VERSION_TYPE_DOS_WORKSTATION = _btrievePython.Btrieve_VERSION_TYPE_DOS_WORKSTATION
    VERSION_TYPE_CLIENT_REQUESTOR = _btrievePython.Btrieve_VERSION_TYPE_CLIENT_REQUESTOR
    VERSION_TYPE_WINDOWS_SERVER_ENGINE = _btrievePython.Btrieve_VERSION_TYPE_WINDOWS_SERVER_ENGINE
    VERSION_TYPE_UNIX = _btrievePython.Btrieve_VERSION_TYPE_UNIX
    VERSION_TYPE_CLIENT_ENGINE = _btrievePython.Btrieve_VERSION_TYPE_CLIENT_ENGINE
    VERSION_TYPE_UNKNOWN = _btrievePython.Btrieve_VERSION_TYPE_UNKNOWN
    if _newclass:
        ACSModeToString = staticmethod(_btrievePython.Btrieve_ACSModeToString)
    else:
        ACSModeToString = _btrievePython.Btrieve_ACSModeToString
    if _newclass:
        DuplicateModeToString = staticmethod(_btrievePython.Btrieve_DuplicateModeToString)
    else:
        DuplicateModeToString = _btrievePython.Btrieve_DuplicateModeToString
    if _newclass:
        DataTypeToString = staticmethod(_btrievePython.Btrieve_DataTypeToString)
    else:
        DataTypeToString = _btrievePython.Btrieve_DataTypeToString
    if _newclass:
        FileVersionToString = staticmethod(_btrievePython.Btrieve_FileVersionToString)
    else:
        FileVersionToString = _btrievePython.Btrieve_FileVersionToString
    if _newclass:
        FreeSpaceThresholdToString = staticmethod(_btrievePython.Btrieve_FreeSpaceThresholdToString)
    else:
        FreeSpaceThresholdToString = _btrievePython.Btrieve_FreeSpaceThresholdToString
    if _newclass:
        IndexToString = staticmethod(_btrievePython.Btrieve_IndexToString)
    else:
        IndexToString = _btrievePython.Btrieve_IndexToString
    if _newclass:
        NullKeyModeToString = staticmethod(_btrievePython.Btrieve_NullKeyModeToString)
    else:
        NullKeyModeToString = _btrievePython.Btrieve_NullKeyModeToString
    if _newclass:
        PageSizeToString = staticmethod(_btrievePython.Btrieve_PageSizeToString)
    else:
        PageSizeToString = _btrievePython.Btrieve_PageSizeToString
    if _newclass:
        RecordCompressionModeToString = staticmethod(_btrievePython.Btrieve_RecordCompressionModeToString)
    else:
        RecordCompressionModeToString = _btrievePython.Btrieve_RecordCompressionModeToString
    if _newclass:
        StatusCodeToString = staticmethod(_btrievePython.Btrieve_StatusCodeToString)
    else:
        StatusCodeToString = _btrievePython.Btrieve_StatusCodeToString
    if _newclass:
        SystemDataModeToString = staticmethod(_btrievePython.Btrieve_SystemDataModeToString)
    else:
        SystemDataModeToString = _btrievePython.Btrieve_SystemDataModeToString
    if _newclass:
        VersionTypeToString = staticmethod(_btrievePython.Btrieve_VersionTypeToString)
    else:
        VersionTypeToString = _btrievePython.Btrieve_VersionTypeToString
    if _newclass:
        PageLockTypeToString = staticmethod(_btrievePython.Btrieve_PageLockTypeToString)
    else:
        PageLockTypeToString = _btrievePython.Btrieve_PageLockTypeToString
    if _newclass:
        LockModeToString = staticmethod(_btrievePython.Btrieve_LockModeToString)
    else:
        LockModeToString = _btrievePython.Btrieve_LockModeToString
    if _newclass:
        OwnerModeToString = staticmethod(_btrievePython.Btrieve_OwnerModeToString)
    else:
        OwnerModeToString = _btrievePython.Btrieve_OwnerModeToString
    if _newclass:
        VariableLengthRecordsModeToString = staticmethod(_btrievePython.Btrieve_VariableLengthRecordsModeToString)
    else:
        VariableLengthRecordsModeToString = _btrievePython.Btrieve_VariableLengthRecordsModeToString
Btrieve_swigregister = _btrievePython.Btrieve_swigregister
Btrieve_swigregister(Btrieve)

def Btrieve_ACSModeToString(ACSMode):
    return _btrievePython.Btrieve_ACSModeToString(ACSMode)
Btrieve_ACSModeToString = _btrievePython.Btrieve_ACSModeToString

def Btrieve_DuplicateModeToString(duplicateMode):
    return _btrievePython.Btrieve_DuplicateModeToString(duplicateMode)
Btrieve_DuplicateModeToString = _btrievePython.Btrieve_DuplicateModeToString

def Btrieve_DataTypeToString(dataType):
    return _btrievePython.Btrieve_DataTypeToString(dataType)
Btrieve_DataTypeToString = _btrievePython.Btrieve_DataTypeToString

def Btrieve_FileVersionToString(fileVersion):
    return _btrievePython.Btrieve_FileVersionToString(fileVersion)
Btrieve_FileVersionToString = _btrievePython.Btrieve_FileVersionToString

def Btrieve_FreeSpaceThresholdToString(freeSpaceThreshold):
    return _btrievePython.Btrieve_FreeSpaceThresholdToString(freeSpaceThreshold)
Btrieve_FreeSpaceThresholdToString = _btrievePython.Btrieve_FreeSpaceThresholdToString

def Btrieve_IndexToString(index):
    return _btrievePython.Btrieve_IndexToString(index)
Btrieve_IndexToString = _btrievePython.Btrieve_IndexToString

def Btrieve_NullKeyModeToString(nullKeyMode):
    return _btrievePython.Btrieve_NullKeyModeToString(nullKeyMode)
Btrieve_NullKeyModeToString = _btrievePython.Btrieve_NullKeyModeToString

def Btrieve_PageSizeToString(pageSize):
    return _btrievePython.Btrieve_PageSizeToString(pageSize)
Btrieve_PageSizeToString = _btrievePython.Btrieve_PageSizeToString

def Btrieve_RecordCompressionModeToString(recordCompressionMode):
    return _btrievePython.Btrieve_RecordCompressionModeToString(recordCompressionMode)
Btrieve_RecordCompressionModeToString = _btrievePython.Btrieve_RecordCompressionModeToString

def Btrieve_StatusCodeToString(statusCode):
    return _btrievePython.Btrieve_StatusCodeToString(statusCode)
Btrieve_StatusCodeToString = _btrievePython.Btrieve_StatusCodeToString

def Btrieve_SystemDataModeToString(systemDataMode):
    return _btrievePython.Btrieve_SystemDataModeToString(systemDataMode)
Btrieve_SystemDataModeToString = _btrievePython.Btrieve_SystemDataModeToString

def Btrieve_VersionTypeToString(versionType):
    return _btrievePython.Btrieve_VersionTypeToString(versionType)
Btrieve_VersionTypeToString = _btrievePython.Btrieve_VersionTypeToString

def Btrieve_PageLockTypeToString(pageLockType):
    return _btrievePython.Btrieve_PageLockTypeToString(pageLockType)
Btrieve_PageLockTypeToString = _btrievePython.Btrieve_PageLockTypeToString

def Btrieve_LockModeToString(lockMode):
    return _btrievePython.Btrieve_LockModeToString(lockMode)
Btrieve_LockModeToString = _btrievePython.Btrieve_LockModeToString

def Btrieve_OwnerModeToString(ownerMode):
    return _btrievePython.Btrieve_OwnerModeToString(ownerMode)
Btrieve_OwnerModeToString = _btrievePython.Btrieve_OwnerModeToString

def Btrieve_VariableLengthRecordsModeToString(variableLengthRecordsMode):
    return _btrievePython.Btrieve_VariableLengthRecordsModeToString(variableLengthRecordsMode)
Btrieve_VariableLengthRecordsModeToString = _btrievePython.Btrieve_VariableLengthRecordsModeToString

class BtrieveClient(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, BtrieveClient, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, BtrieveClient, name)
    __repr__ = _swig_repr

    def __init__(self, serviceAgentIdentifier, clientIdentifier):
        this = _btrievePython.new_BtrieveClient(serviceAgentIdentifier, clientIdentifier)
        try:
            self.this.append(this)
        except __builtin__.Exception:
            self.this = this
    __swig_destroy__ = _btrievePython.delete_BtrieveClient
    __del__ = lambda self: None

    def GetVersion(self, btrieveVersion, btrieveFile=None):
        return _btrievePython.BtrieveClient_GetVersion(self, btrieveVersion, btrieveFile)

    def FileOpen(self, *args):
        return _btrievePython.BtrieveClient_FileOpen(self, *args)

    def GetCurrentDirectory(self, *args):
        return _btrievePython.BtrieveClient_GetCurrentDirectory(self, *args)

    def ContinuousOperationBegin(self, *args):
        return _btrievePython.BtrieveClient_ContinuousOperationBegin(self, *args)

    def ContinuousOperationEnd(self, *args):
        return _btrievePython.BtrieveClient_ContinuousOperationEnd(self, *args)

    def FileClose(self, btrieveFile):
        return _btrievePython.BtrieveClient_FileClose(self, btrieveFile)

    def FileCreate(self, *args):
        return _btrievePython.BtrieveClient_FileCreate(self, *args)

    def FileDelete(self, *args):
        return _btrievePython.BtrieveClient_FileDelete(self, *args)

    def FileRename(self, *args):
        return _btrievePython.BtrieveClient_FileRename(self, *args)

    def GetLastStatusCode(self):
        return _btrievePython.BtrieveClient_GetLastStatusCode(self)

    def Login(self, *args):
        return _btrievePython.BtrieveClient_Login(self, *args)

    def Logout(self, *args):
        return _btrievePython.BtrieveClient_Logout(self, *args)

    def Reset(self):
        return _btrievePython.BtrieveClient_Reset(self)

    def SetCurrentDirectory(self, *args):
        return _btrievePython.BtrieveClient_SetCurrentDirectory(self, *args)

    def Stop(self):
        return _btrievePython.BtrieveClient_Stop(self)

    def TransactionAbort(self):
        return _btrievePython.BtrieveClient_TransactionAbort(self)

    def TransactionBegin(self, *args):
        return _btrievePython.BtrieveClient_TransactionBegin(self, *args)

    def TransactionEnd(self):
        return _btrievePython.BtrieveClient_TransactionEnd(self)

    def GetServiceAgentIdentifier(self):
        return _btrievePython.BtrieveClient_GetServiceAgentIdentifier(self)

    def GetClientIdentifier(self):
        return _btrievePython.BtrieveClient_GetClientIdentifier(self)
BtrieveClient_swigregister = _btrievePython.BtrieveClient_swigregister
BtrieveClient_swigregister(BtrieveClient)

class BtrieveFile(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, BtrieveFile, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, BtrieveFile, name)
    __repr__ = _swig_repr

    def __init__(self):
        this = _btrievePython.new_BtrieveFile()
        try:
            self.this.append(this)
        except __builtin__.Exception:
            self.this = this
    __swig_destroy__ = _btrievePython.delete_BtrieveFile
    __del__ = lambda self: None

    def RecordDelete(self):
        return _btrievePython.BtrieveFile_RecordDelete(self)

    def BulkRetrieveNext(self, *args):
        return _btrievePython.BtrieveFile_BulkRetrieveNext(self, *args)

    def BulkRetrievePrevious(self, *args):
        return _btrievePython.BtrieveFile_BulkRetrievePrevious(self, *args)

    def GetInformation(self, btrieveFileInformation):
        return _btrievePython.BtrieveFile_GetInformation(self, btrieveFileInformation)

    def GetLastStatusCode(self):
        return _btrievePython.BtrieveFile_GetLastStatusCode(self)

    def GetCursorPosition(self):
        return _btrievePython.BtrieveFile_GetCursorPosition(self)

    def IndexCreate(self, btrieveIndexAttributes):
        return _btrievePython.BtrieveFile_IndexCreate(self, btrieveIndexAttributes)

    def IndexDrop(self, index):
        return _btrievePython.BtrieveFile_IndexDrop(self, index)

    def BulkCreate(self, btrieveBulkCreatePayload, btrieveBulkCreateResult):
        return _btrievePython.BtrieveFile_BulkCreate(self, btrieveBulkCreatePayload, btrieveBulkCreateResult)

    def SetOwner(self, ownerMode, ownerName=None, ownerNameAgain=None, useLongOwnerName=True):
        return _btrievePython.BtrieveFile_SetOwner(self, ownerMode, ownerName, ownerNameAgain, useLongOwnerName)

    def RecordTruncate(self, *args):
        return _btrievePython.BtrieveFile_RecordTruncate(self, *args)

    def RecordUnlock(self, unlockMode):
        return _btrievePython.BtrieveFile_RecordUnlock(self, unlockMode)

    def UnlockCursorPosition(self, cursorPosition):
        return _btrievePython.BtrieveFile_UnlockCursorPosition(self, cursorPosition)

    def GetNumerator(self, index, keyObject, denominator):
        return _btrievePython.BtrieveFile_GetNumerator(self, index, keyObject, denominator)

    def GetPercentage(self, index, keyObject):
        return _btrievePython.BtrieveFile_GetPercentage(self, index, keyObject)

    def KeyRetrieve(self, comparison, index, keyObject):
        return _btrievePython.BtrieveFile_KeyRetrieve(self, comparison, index, keyObject)

    def KeyRetrieveFirst(self, index, keyObject):
        return _btrievePython.BtrieveFile_KeyRetrieveFirst(self, index, keyObject)

    def KeyRetrieveLast(self, index, keyObject):
        return _btrievePython.BtrieveFile_KeyRetrieveLast(self, index, keyObject)

    def KeyRetrieveNext(self, keyObject):
        return _btrievePython.BtrieveFile_KeyRetrieveNext(self, keyObject)

    def KeyRetrievePrevious(self, keyObject):
        return _btrievePython.BtrieveFile_KeyRetrievePrevious(self, keyObject)

    def RecordAppendChunk(self, chunkObject):
        return _btrievePython.BtrieveFile_RecordAppendChunk(self, chunkObject)

    def RecordCreate(self, recordObject):
        return _btrievePython.BtrieveFile_RecordCreate(self, recordObject)

    def RecordRetrieveByCursorPosition(self, *args):
        return _btrievePython.BtrieveFile_RecordRetrieveByCursorPosition(self, *args)

    def RecordRetrieveByFraction(self, *args):
        return _btrievePython.BtrieveFile_RecordRetrieveByFraction(self, *args)

    def RecordRetrieveByPercentage(self, *args):
        return _btrievePython.BtrieveFile_RecordRetrieveByPercentage(self, *args)

    def RecordRetrieveChunk(self, *args):
        return _btrievePython.BtrieveFile_RecordRetrieveChunk(self, *args)

    def RecordRetrieve(self, *args):
        return _btrievePython.BtrieveFile_RecordRetrieve(self, *args)

    def RecordRetrieveFirst(self, *args):
        return _btrievePython.BtrieveFile_RecordRetrieveFirst(self, *args)

    def RecordRetrieveLast(self, *args):
        return _btrievePython.BtrieveFile_RecordRetrieveLast(self, *args)

    def RecordRetrieveNext(self, *args):
        return _btrievePython.BtrieveFile_RecordRetrieveNext(self, *args)

    def RecordRetrievePrevious(self, *args):
        return _btrievePython.BtrieveFile_RecordRetrievePrevious(self, *args)

    def RecordUpdate(self, recordObject):
        return _btrievePython.BtrieveFile_RecordUpdate(self, recordObject)

    def RecordUpdateChunk(self, *args):
        return _btrievePython.BtrieveFile_RecordUpdateChunk(self, *args)
BtrieveFile_swigregister = _btrievePython.BtrieveFile_swigregister
BtrieveFile_swigregister(BtrieveFile)

class BtrieveFileAttributes(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, BtrieveFileAttributes, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, BtrieveFileAttributes, name)
    __repr__ = _swig_repr

    def __init__(self):
        this = _btrievePython.new_BtrieveFileAttributes()
        try:
            self.this.append(this)
        except __builtin__.Exception:
            self.this = this
    __swig_destroy__ = _btrievePython.delete_BtrieveFileAttributes
    __del__ = lambda self: None

    def SetBalancedIndexes(self, enableBalancedIndexes):
        return _btrievePython.BtrieveFileAttributes_SetBalancedIndexes(self, enableBalancedIndexes)

    def SetRecordCompressionMode(self, recordCompressionMode):
        return _btrievePython.BtrieveFileAttributes_SetRecordCompressionMode(self, recordCompressionMode)

    def SetReservedDuplicatePointerCount(self, reservedDuplicatePointerCount):
        return _btrievePython.BtrieveFileAttributes_SetReservedDuplicatePointerCount(self, reservedDuplicatePointerCount)

    def SetFileVersion(self, fileVersion):
        return _btrievePython.BtrieveFileAttributes_SetFileVersion(self, fileVersion)

    def SetFreeSpaceThreshold(self, freeSpaceThreshold):
        return _btrievePython.BtrieveFileAttributes_SetFreeSpaceThreshold(self, freeSpaceThreshold)

    def SetPageSize(self, pageSize, enablePageCompression=False):
        return _btrievePython.BtrieveFileAttributes_SetPageSize(self, pageSize, enablePageCompression)

    def SetFixedRecordLength(self, fixedRecordLength):
        return _btrievePython.BtrieveFileAttributes_SetFixedRecordLength(self, fixedRecordLength)

    def SetPreallocatedPageCount(self, preallocatedPageCount):
        return _btrievePython.BtrieveFileAttributes_SetPreallocatedPageCount(self, preallocatedPageCount)

    def SetSystemDataMode(self, systemDataMode):
        return _btrievePython.BtrieveFileAttributes_SetSystemDataMode(self, systemDataMode)

    def SetVariableLengthRecordsMode(self, variableLengthRecordsMode):
        return _btrievePython.BtrieveFileAttributes_SetVariableLengthRecordsMode(self, variableLengthRecordsMode)

    def SetKeyOnly(self, enableKeyOnly):
        return _btrievePython.BtrieveFileAttributes_SetKeyOnly(self, enableKeyOnly)
BtrieveFileAttributes_swigregister = _btrievePython.BtrieveFileAttributes_swigregister
BtrieveFileAttributes_swigregister(BtrieveFileAttributes)

class BtrieveFileInformation(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, BtrieveFileInformation, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, BtrieveFileInformation, name)
    __repr__ = _swig_repr

    def __init__(self):
        this = _btrievePython.new_BtrieveFileInformation()
        try:
            self.this.append(this)
        except __builtin__.Exception:
            self.this = this
    __swig_destroy__ = _btrievePython.delete_BtrieveFileInformation
    __del__ = lambda self: None

    def GetLastStatusCode(self):
        return _btrievePython.BtrieveFileInformation_GetLastStatusCode(self)

    def GetFileVersion(self):
        return _btrievePython.BtrieveFileInformation_GetFileVersion(self)

    def GetFreeSpaceThreshold(self):
        return _btrievePython.BtrieveFileInformation_GetFreeSpaceThreshold(self)

    def GetPageSize(self):
        return _btrievePython.BtrieveFileInformation_GetPageSize(self)

    def GetSystemDataMode(self):
        return _btrievePython.BtrieveFileInformation_GetSystemDataMode(self)

    def GetKeySegment(self, btrieveKeySegment, keySegmentNumber):
        return _btrievePython.BtrieveFileInformation_GetKeySegment(self, btrieveKeySegment, keySegmentNumber)

    def GetBalancedIndexes(self):
        return _btrievePython.BtrieveFileInformation_GetBalancedIndexes(self)

    def GetRecordCompressionMode(self):
        return _btrievePython.BtrieveFileInformation_GetRecordCompressionMode(self)

    def GetKeyOnly(self):
        return _btrievePython.BtrieveFileInformation_GetKeyOnly(self)

    def GetPageCompression(self):
        return _btrievePython.BtrieveFileInformation_GetPageCompression(self)

    def GetPagePreallocation(self):
        return _btrievePython.BtrieveFileInformation_GetPagePreallocation(self)

    def GetVariableLengthRecordsMode(self):
        return _btrievePython.BtrieveFileInformation_GetVariableLengthRecordsMode(self)

    def GetUnusedDuplicatePointerCount(self):
        return _btrievePython.BtrieveFileInformation_GetUnusedDuplicatePointerCount(self)

    def GetIndexCount(self):
        return _btrievePython.BtrieveFileInformation_GetIndexCount(self)

    def GetFixedRecordLength(self):
        return _btrievePython.BtrieveFileInformation_GetFixedRecordLength(self)

    def GetRecordCount(self):
        return _btrievePython.BtrieveFileInformation_GetRecordCount(self)

    def GetSegmented(self):
        return _btrievePython.BtrieveFileInformation_GetSegmented(self)

    def GetUnusedPageCount(self):
        return _btrievePython.BtrieveFileInformation_GetUnusedPageCount(self)

    def GetLogIndex(self):
        return _btrievePython.BtrieveFileInformation_GetLogIndex(self)

    def GetLoggable(self):
        return _btrievePython.BtrieveFileInformation_GetLoggable(self)

    def GetSystemIndexPresent(self):
        return _btrievePython.BtrieveFileInformation_GetSystemIndexPresent(self)

    def GetSystemIndexSize(self):
        return _btrievePython.BtrieveFileInformation_GetSystemIndexSize(self)

    def GetSystemIndexUsed(self):
        return _btrievePython.BtrieveFileInformation_GetSystemIndexUsed(self)

    def GetSystemIndexVersion(self):
        return _btrievePython.BtrieveFileInformation_GetSystemIndexVersion(self)

    def GetDuplicateRecordConflictCursorPosition(self):
        return _btrievePython.BtrieveFileInformation_GetDuplicateRecordConflictCursorPosition(self)

    def GetDuplicateRecordConflictIndex(self):
        return _btrievePython.BtrieveFileInformation_GetDuplicateRecordConflictIndex(self)

    def GetIdentifier(self):
        return _btrievePython.BtrieveFileInformation_GetIdentifier(self)

    def GetHandleCount(self):
        return _btrievePython.BtrieveFileInformation_GetHandleCount(self)

    def GetOpenTimestamp(self):
        return _btrievePython.BtrieveFileInformation_GetOpenTimestamp(self)

    def GetUsageCount(self):
        return _btrievePython.BtrieveFileInformation_GetUsageCount(self)

    def GetExplicitLocks(self):
        return _btrievePython.BtrieveFileInformation_GetExplicitLocks(self)

    def GetClientTransactions(self):
        return _btrievePython.BtrieveFileInformation_GetClientTransactions(self)

    def GetReadOnly(self):
        return _btrievePython.BtrieveFileInformation_GetReadOnly(self)

    def GetContinuousOperation(self):
        return _btrievePython.BtrieveFileInformation_GetContinuousOperation(self)

    def GetReferentialIntegrityConstraints(self):
        return _btrievePython.BtrieveFileInformation_GetReferentialIntegrityConstraints(self)

    def GetOwnerMode(self):
        return _btrievePython.BtrieveFileInformation_GetOwnerMode(self)

    def GetWrongOwner(self):
        return _btrievePython.BtrieveFileInformation_GetWrongOwner(self)

    def GetGatewayMajorVersion(self):
        return _btrievePython.BtrieveFileInformation_GetGatewayMajorVersion(self)

    def GetGatewayMinorVersion(self):
        return _btrievePython.BtrieveFileInformation_GetGatewayMinorVersion(self)

    def GetGatewayPatchLevel(self):
        return _btrievePython.BtrieveFileInformation_GetGatewayPatchLevel(self)

    def GetGatewayPlatform(self):
        return _btrievePython.BtrieveFileInformation_GetGatewayPlatform(self)

    def GetGatewayName(self):
        return _btrievePython.BtrieveFileInformation_GetGatewayName(self)

    def GetLockOwnerImplicitLock(self):
        return _btrievePython.BtrieveFileInformation_GetLockOwnerImplicitLock(self)

    def GetLockOwnerFileLock(self):
        return _btrievePython.BtrieveFileInformation_GetLockOwnerFileLock(self)

    def GetLockOwnerRecordLock(self):
        return _btrievePython.BtrieveFileInformation_GetLockOwnerRecordLock(self)

    def GetLockOwnerSameProcess(self):
        return _btrievePython.BtrieveFileInformation_GetLockOwnerSameProcess(self)

    def GetLockOwnerWriteNoWait(self):
        return _btrievePython.BtrieveFileInformation_GetLockOwnerWriteNoWait(self)

    def GetLockOwnerWriteHold(self):
        return _btrievePython.BtrieveFileInformation_GetLockOwnerWriteHold(self)

    def GetLockOwnerTimeInTransaction(self):
        return _btrievePython.BtrieveFileInformation_GetLockOwnerTimeInTransaction(self)

    def GetLockOwnerTransactionLevel(self):
        return _btrievePython.BtrieveFileInformation_GetLockOwnerTransactionLevel(self)

    def GetLockOwnerName(self):
        return _btrievePython.BtrieveFileInformation_GetLockOwnerName(self)

    def GetLockOwnerServiceAgentIdentifier(self):
        return _btrievePython.BtrieveFileInformation_GetLockOwnerServiceAgentIdentifier(self)

    def GetLockOwnerClientIdentifier(self):
        return _btrievePython.BtrieveFileInformation_GetLockOwnerClientIdentifier(self)

    def GetLockOwnerExplicitLockMode(self):
        return _btrievePython.BtrieveFileInformation_GetLockOwnerExplicitLockMode(self)

    def GetLockOwnerPageLockType(self):
        return _btrievePython.BtrieveFileInformation_GetLockOwnerPageLockType(self)

    def GetLockOwnerIndex(self):
        return _btrievePython.BtrieveFileInformation_GetLockOwnerIndex(self)

    def GetReferentialIntegrityFileName(self):
        return _btrievePython.BtrieveFileInformation_GetReferentialIntegrityFileName(self)

    def GetReferentialIntegrityOperationCode(self):
        return _btrievePython.BtrieveFileInformation_GetReferentialIntegrityOperationCode(self)

    def GetReferentialIntegrityCursorPosition(self):
        return _btrievePython.BtrieveFileInformation_GetReferentialIntegrityCursorPosition(self)

    def GetSegmentCount(self):
        return _btrievePython.BtrieveFileInformation_GetSegmentCount(self)

    def GetSegmentFileName(self, segmentFileNumber):
        return _btrievePython.BtrieveFileInformation_GetSegmentFileName(self, segmentFileNumber)

    def GetSecurityHandleTrusted(self):
        return _btrievePython.BtrieveFileInformation_GetSecurityHandleTrusted(self)

    def GetSecurityHandleImplicit(self):
        return _btrievePython.BtrieveFileInformation_GetSecurityHandleImplicit(self)

    def GetSecurityHandleExplicit(self):
        return _btrievePython.BtrieveFileInformation_GetSecurityHandleExplicit(self)

    def GetSecurityHandleAuthenticationByDatabase(self):
        return _btrievePython.BtrieveFileInformation_GetSecurityHandleAuthenticationByDatabase(self)

    def GetSecurityHandleAuthorizationByDatabase(self):
        return _btrievePython.BtrieveFileInformation_GetSecurityHandleAuthorizationByDatabase(self)

    def GetSecurityHandleWindowsNamedPipe(self):
        return _btrievePython.BtrieveFileInformation_GetSecurityHandleWindowsNamedPipe(self)

    def GetSecurityHandleWorkgroup(self):
        return _btrievePython.BtrieveFileInformation_GetSecurityHandleWorkgroup(self)

    def GetSecurityHandleBtpasswd(self):
        return _btrievePython.BtrieveFileInformation_GetSecurityHandleBtpasswd(self)

    def GetSecurityHandlePAM(self):
        return _btrievePython.BtrieveFileInformation_GetSecurityHandlePAM(self)

    def GetSecurityHandleRTSSComplete(self):
        return _btrievePython.BtrieveFileInformation_GetSecurityHandleRTSSComplete(self)

    def GetSecurityHandleRTSSPreauthorized(self):
        return _btrievePython.BtrieveFileInformation_GetSecurityHandleRTSSPreauthorized(self)

    def GetSecurityHandleRTSSDisabled(self):
        return _btrievePython.BtrieveFileInformation_GetSecurityHandleRTSSDisabled(self)

    def GetSecurityCurrentDatabaseTrusted(self):
        return _btrievePython.BtrieveFileInformation_GetSecurityCurrentDatabaseTrusted(self)

    def GetSecurityCurrentDatabaseImplicit(self):
        return _btrievePython.BtrieveFileInformation_GetSecurityCurrentDatabaseImplicit(self)

    def GetSecurityCurrentDatabaseExplicit(self):
        return _btrievePython.BtrieveFileInformation_GetSecurityCurrentDatabaseExplicit(self)

    def GetSecurityCurrentDatabaseAuthenticationByDatabase(self):
        return _btrievePython.BtrieveFileInformation_GetSecurityCurrentDatabaseAuthenticationByDatabase(self)

    def GetSecurityCurrentDatabaseAuthorizationByDatabase(self):
        return _btrievePython.BtrieveFileInformation_GetSecurityCurrentDatabaseAuthorizationByDatabase(self)

    def GetSecurityCurrentDatabaseWindowsNamedPipe(self):
        return _btrievePython.BtrieveFileInformation_GetSecurityCurrentDatabaseWindowsNamedPipe(self)

    def GetSecurityCurrentDatabaseWorkgroup(self):
        return _btrievePython.BtrieveFileInformation_GetSecurityCurrentDatabaseWorkgroup(self)

    def GetSecurityCurrentDatabaseBtpasswd(self):
        return _btrievePython.BtrieveFileInformation_GetSecurityCurrentDatabaseBtpasswd(self)

    def GetSecurityCurrentDatabasePAM(self):
        return _btrievePython.BtrieveFileInformation_GetSecurityCurrentDatabasePAM(self)

    def GetSecurityCurrentDatabaseRTSSComplete(self):
        return _btrievePython.BtrieveFileInformation_GetSecurityCurrentDatabaseRTSSComplete(self)

    def GetSecurityCurrentDatabaseRTSSPreauthorized(self):
        return _btrievePython.BtrieveFileInformation_GetSecurityCurrentDatabaseRTSSPreauthorized(self)

    def GetSecurityCurrentDatabaseRTSSDisabled(self):
        return _btrievePython.BtrieveFileInformation_GetSecurityCurrentDatabaseRTSSDisabled(self)

    def GetSecurityPermissionNoRights(self):
        return _btrievePython.BtrieveFileInformation_GetSecurityPermissionNoRights(self)

    def GetSecurityPermissionOpen(self):
        return _btrievePython.BtrieveFileInformation_GetSecurityPermissionOpen(self)

    def GetSecurityPermissionRead(self):
        return _btrievePython.BtrieveFileInformation_GetSecurityPermissionRead(self)

    def GetSecurityPermissionCreateFile(self):
        return _btrievePython.BtrieveFileInformation_GetSecurityPermissionCreateFile(self)

    def GetSecurityPermissionUpdate(self):
        return _btrievePython.BtrieveFileInformation_GetSecurityPermissionUpdate(self)

    def GetSecurityPermissionCreateRecord(self):
        return _btrievePython.BtrieveFileInformation_GetSecurityPermissionCreateRecord(self)

    def GetSecurityPermissionDelete(self):
        return _btrievePython.BtrieveFileInformation_GetSecurityPermissionDelete(self)

    def GetSecurityPermissionExecute(self):
        return _btrievePython.BtrieveFileInformation_GetSecurityPermissionExecute(self)

    def GetSecurityPermissionAlter(self):
        return _btrievePython.BtrieveFileInformation_GetSecurityPermissionAlter(self)

    def GetSecurityPermissionRefer(self):
        return _btrievePython.BtrieveFileInformation_GetSecurityPermissionRefer(self)

    def GetSecurityPermissionCreateView(self):
        return _btrievePython.BtrieveFileInformation_GetSecurityPermissionCreateView(self)

    def GetSecurityPermissionCreateStoredProcedure(self):
        return _btrievePython.BtrieveFileInformation_GetSecurityPermissionCreateStoredProcedure(self)

    def GetSecurityHandleDatabaseName(self):
        return _btrievePython.BtrieveFileInformation_GetSecurityHandleDatabaseName(self)

    def GetSecurityHandleTableName(self):
        return _btrievePython.BtrieveFileInformation_GetSecurityHandleTableName(self)

    def GetSecurityHandleUserName(self):
        return _btrievePython.BtrieveFileInformation_GetSecurityHandleUserName(self)

    def GetSecurityCurrentDatabaseName(self):
        return _btrievePython.BtrieveFileInformation_GetSecurityCurrentDatabaseName(self)

    def GetSecurityCurrentUserName(self):
        return _btrievePython.BtrieveFileInformation_GetSecurityCurrentUserName(self)
BtrieveFileInformation_swigregister = _btrievePython.BtrieveFileInformation_swigregister
BtrieveFileInformation_swigregister(BtrieveFileInformation)

class BtrieveFilter(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, BtrieveFilter, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, BtrieveFilter, name)
    __repr__ = _swig_repr

    def __init__(self):
        this = _btrievePython.new_BtrieveFilter()
        try:
            self.this.append(this)
        except __builtin__.Exception:
            self.this = this
    __swig_destroy__ = _btrievePython.delete_BtrieveFilter
    __del__ = lambda self: None

    def SetComparison(self, comparison):
        return _btrievePython.BtrieveFilter_SetComparison(self, comparison)

    def SetComparisonField(self, offset):
        return _btrievePython.BtrieveFilter_SetComparisonField(self, offset)

    def SetField(self, offset, length, dataType):
        return _btrievePython.BtrieveFilter_SetField(self, offset, length, dataType)

    def SetLikeCodePageName(self, name):
        return _btrievePython.BtrieveFilter_SetLikeCodePageName(self, name)

    def SetConnector(self, connector):
        return _btrievePython.BtrieveFilter_SetConnector(self, connector)

    def SetACSMode(self, ACSMode):
        return _btrievePython.BtrieveFilter_SetACSMode(self, ACSMode)

    def SetACSUserDefined(self, name):
        return _btrievePython.BtrieveFilter_SetACSUserDefined(self, name)

    def SetACSName(self, name):
        return _btrievePython.BtrieveFilter_SetACSName(self, name)

    def SetComparisonConstant(self, constantObject):
        return _btrievePython.BtrieveFilter_SetComparisonConstant(self, constantObject)
BtrieveFilter_swigregister = _btrievePython.BtrieveFilter_swigregister
BtrieveFilter_swigregister(BtrieveFilter)

class BtrieveBulkRetrieveAttributes(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, BtrieveBulkRetrieveAttributes, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, BtrieveBulkRetrieveAttributes, name)
    __repr__ = _swig_repr

    def __init__(self):
        this = _btrievePython.new_BtrieveBulkRetrieveAttributes()
        try:
            self.this.append(this)
        except __builtin__.Exception:
            self.this = this
    __swig_destroy__ = _btrievePython.delete_BtrieveBulkRetrieveAttributes
    __del__ = lambda self: None

    def AddField(self, offset, length):
        return _btrievePython.BtrieveBulkRetrieveAttributes_AddField(self, offset, length)

    def AddFilter(self, btrieveFilter):
        return _btrievePython.BtrieveBulkRetrieveAttributes_AddFilter(self, btrieveFilter)

    def SetMaximumRecordCount(self, maximumRecordCount):
        return _btrievePython.BtrieveBulkRetrieveAttributes_SetMaximumRecordCount(self, maximumRecordCount)

    def SetMaximumRejectCount(self, maximumRejectCount):
        return _btrievePython.BtrieveBulkRetrieveAttributes_SetMaximumRejectCount(self, maximumRejectCount)

    def SetSkipCurrentRecord(self, skipCurrentRecord):
        return _btrievePython.BtrieveBulkRetrieveAttributes_SetSkipCurrentRecord(self, skipCurrentRecord)
BtrieveBulkRetrieveAttributes_swigregister = _btrievePython.BtrieveBulkRetrieveAttributes_swigregister
BtrieveBulkRetrieveAttributes_swigregister(BtrieveBulkRetrieveAttributes)

class BtrieveBulkRetrieveResult(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, BtrieveBulkRetrieveResult, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, BtrieveBulkRetrieveResult, name)
    __repr__ = _swig_repr

    def __init__(self):
        this = _btrievePython.new_BtrieveBulkRetrieveResult()
        try:
            self.this.append(this)
        except __builtin__.Exception:
            self.this = this
    __swig_destroy__ = _btrievePython.delete_BtrieveBulkRetrieveResult
    __del__ = lambda self: None

    def GetLastStatusCode(self):
        return _btrievePython.BtrieveBulkRetrieveResult_GetLastStatusCode(self)

    def GetRecordCount(self):
        return _btrievePython.BtrieveBulkRetrieveResult_GetRecordCount(self)

    def GetRecordLength(self, recordNumber):
        return _btrievePython.BtrieveBulkRetrieveResult_GetRecordLength(self, recordNumber)

    def GetRecordCursorPosition(self, recordNumber):
        return _btrievePython.BtrieveBulkRetrieveResult_GetRecordCursorPosition(self, recordNumber)

    def GetRecord(self, recordNumber, recordObject):
        return _btrievePython.BtrieveBulkRetrieveResult_GetRecord(self, recordNumber, recordObject)
BtrieveBulkRetrieveResult_swigregister = _btrievePython.BtrieveBulkRetrieveResult_swigregister
BtrieveBulkRetrieveResult_swigregister(BtrieveBulkRetrieveResult)

class BtrieveIndexAttributes(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, BtrieveIndexAttributes, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, BtrieveIndexAttributes, name)
    __repr__ = _swig_repr

    def __init__(self):
        this = _btrievePython.new_BtrieveIndexAttributes()
        try:
            self.this.append(this)
        except __builtin__.Exception:
            self.this = this
    __swig_destroy__ = _btrievePython.delete_BtrieveIndexAttributes
    __del__ = lambda self: None

    def AddKeySegment(self, btrieveKeySegment):
        return _btrievePython.BtrieveIndexAttributes_AddKeySegment(self, btrieveKeySegment)

    def SetIndex(self, index):
        return _btrievePython.BtrieveIndexAttributes_SetIndex(self, index)

    def SetDuplicateMode(self, duplicateMode):
        return _btrievePython.BtrieveIndexAttributes_SetDuplicateMode(self, duplicateMode)

    def SetModifiable(self, enableModifiable):
        return _btrievePython.BtrieveIndexAttributes_SetModifiable(self, enableModifiable)

    def SetACSMode(self, ACSMode):
        return _btrievePython.BtrieveIndexAttributes_SetACSMode(self, ACSMode)

    def SetACSName(self, ACSName):
        return _btrievePython.BtrieveIndexAttributes_SetACSName(self, ACSName)

    def SetACSNumber(self, ACSNumber):
        return _btrievePython.BtrieveIndexAttributes_SetACSNumber(self, ACSNumber)

    def SetACSUserDefined(self, ACSName, ACSMapObject):
        return _btrievePython.BtrieveIndexAttributes_SetACSUserDefined(self, ACSName, ACSMapObject)
BtrieveIndexAttributes_swigregister = _btrievePython.BtrieveIndexAttributes_swigregister
BtrieveIndexAttributes_swigregister(BtrieveIndexAttributes)

class BtrieveBulkCreatePayload(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, BtrieveBulkCreatePayload, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, BtrieveBulkCreatePayload, name)
    __repr__ = _swig_repr

    def __init__(self):
        this = _btrievePython.new_BtrieveBulkCreatePayload()
        try:
            self.this.append(this)
        except __builtin__.Exception:
            self.this = this
    __swig_destroy__ = _btrievePython.delete_BtrieveBulkCreatePayload
    __del__ = lambda self: None

    def AddRecord(self, recordObject):
        return _btrievePython.BtrieveBulkCreatePayload_AddRecord(self, recordObject)
BtrieveBulkCreatePayload_swigregister = _btrievePython.BtrieveBulkCreatePayload_swigregister
BtrieveBulkCreatePayload_swigregister(BtrieveBulkCreatePayload)

class BtrieveBulkCreateResult(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, BtrieveBulkCreateResult, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, BtrieveBulkCreateResult, name)
    __repr__ = _swig_repr

    def __init__(self):
        this = _btrievePython.new_BtrieveBulkCreateResult()
        try:
            self.this.append(this)
        except __builtin__.Exception:
            self.this = this
    __swig_destroy__ = _btrievePython.delete_BtrieveBulkCreateResult
    __del__ = lambda self: None

    def GetLastStatusCode(self):
        return _btrievePython.BtrieveBulkCreateResult_GetLastStatusCode(self)

    def GetRecordCount(self):
        return _btrievePython.BtrieveBulkCreateResult_GetRecordCount(self)

    def GetRecordCursorPosition(self, recordNumber):
        return _btrievePython.BtrieveBulkCreateResult_GetRecordCursorPosition(self, recordNumber)
BtrieveBulkCreateResult_swigregister = _btrievePython.BtrieveBulkCreateResult_swigregister
BtrieveBulkCreateResult_swigregister(BtrieveBulkCreateResult)

class BtrieveKeySegment(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, BtrieveKeySegment, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, BtrieveKeySegment, name)
    __repr__ = _swig_repr

    def __init__(self):
        this = _btrievePython.new_BtrieveKeySegment()
        try:
            self.this.append(this)
        except __builtin__.Exception:
            self.this = this
    __swig_destroy__ = _btrievePython.delete_BtrieveKeySegment
    __del__ = lambda self: None

    def GetLastStatusCode(self):
        return _btrievePython.BtrieveKeySegment_GetLastStatusCode(self)

    def GetACSMode(self):
        return _btrievePython.BtrieveKeySegment_GetACSMode(self)

    def GetModifiable(self):
        return _btrievePython.BtrieveKeySegment_GetModifiable(self)

    def GetKeyContinues(self):
        return _btrievePython.BtrieveKeySegment_GetKeyContinues(self)

    def GetDataType(self):
        return _btrievePython.BtrieveKeySegment_GetDataType(self)

    def GetACSNumber(self):
        return _btrievePython.BtrieveKeySegment_GetACSNumber(self)

    def GetDescendingSortOrder(self):
        return _btrievePython.BtrieveKeySegment_GetDescendingSortOrder(self)

    def GetDuplicateMode(self):
        return _btrievePython.BtrieveKeySegment_GetDuplicateMode(self)

    def GetIndex(self):
        return _btrievePython.BtrieveKeySegment_GetIndex(self)

    def GetLength(self):
        return _btrievePython.BtrieveKeySegment_GetLength(self)

    def GetNullKeyMode(self):
        return _btrievePython.BtrieveKeySegment_GetNullKeyMode(self)

    def GetNullValue(self):
        return _btrievePython.BtrieveKeySegment_GetNullValue(self)

    def GetOffset(self):
        return _btrievePython.BtrieveKeySegment_GetOffset(self)

    def GetUniqueValueCount(self):
        return _btrievePython.BtrieveKeySegment_GetUniqueValueCount(self)

    def SetDescendingSortOrder(self, setDescendingSortOrder):
        return _btrievePython.BtrieveKeySegment_SetDescendingSortOrder(self, setDescendingSortOrder)

    def SetField(self, offset, length, dataType):
        return _btrievePython.BtrieveKeySegment_SetField(self, offset, length, dataType)

    def SetNullKeyMode(self, nullKeyMode):
        return _btrievePython.BtrieveKeySegment_SetNullKeyMode(self, nullKeyMode)

    def SetNullValue(self, nullValue):
        return _btrievePython.BtrieveKeySegment_SetNullValue(self, nullValue)
BtrieveKeySegment_swigregister = _btrievePython.BtrieveKeySegment_swigregister
BtrieveKeySegment_swigregister(BtrieveKeySegment)

class BtrieveVersion(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, BtrieveVersion, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, BtrieveVersion, name)
    __repr__ = _swig_repr

    def __init__(self):
        this = _btrievePython.new_BtrieveVersion()
        try:
            self.this.append(this)
        except __builtin__.Exception:
            self.this = this
    __swig_destroy__ = _btrievePython.delete_BtrieveVersion
    __del__ = lambda self: None

    def GetLastStatusCode(self):
        return _btrievePython.BtrieveVersion_GetLastStatusCode(self)

    def GetClientVersionType(self):
        return _btrievePython.BtrieveVersion_GetClientVersionType(self)

    def GetRemoteVersionType(self):
        return _btrievePython.BtrieveVersion_GetRemoteVersionType(self)

    def GetLocalVersionType(self):
        return _btrievePython.BtrieveVersion_GetLocalVersionType(self)

    def GetClientRevisionNumber(self):
        return _btrievePython.BtrieveVersion_GetClientRevisionNumber(self)

    def GetClientVersionNumber(self):
        return _btrievePython.BtrieveVersion_GetClientVersionNumber(self)

    def GetRemoteRevisionNumber(self):
        return _btrievePython.BtrieveVersion_GetRemoteRevisionNumber(self)

    def GetRemoteVersionNumber(self):
        return _btrievePython.BtrieveVersion_GetRemoteVersionNumber(self)

    def GetLocalRevisionNumber(self):
        return _btrievePython.BtrieveVersion_GetLocalRevisionNumber(self)

    def GetLocalVersionNumber(self):
        return _btrievePython.BtrieveVersion_GetLocalVersionNumber(self)
BtrieveVersion_swigregister = _btrievePython.BtrieveVersion_swigregister
BtrieveVersion_swigregister(BtrieveVersion)

# This file is compatible with both classic and new-style classes.


